from pathlib import Path
from PIL import Image
from lxml import html
import re

root=Path(__file__).parent
assets=root/'assets'
cover=Path('/workspace/scratch/1380a0196d99/Study_57_The_Eternal_Purpose_of_God_COVER_REVIEW.png')
pdf=Path('/workspace/scratch/1380a0196d99/study57-final-render')
im=Image.open(cover).convert('RGB')
im.resize((960,1440),Image.Resampling.LANCZOS).save(assets/'study-57-cover.jpg',quality=92,optimize=True)
im.resize((960,1440),Image.Resampling.LANCZOS).save(assets/'study-57-cover.webp',quality=88)
for physical,interior in [(4,3),(7,6),(11,10)]:
    page=Image.open(pdf/f'page-{physical}.png').convert('RGB')
    page.save(assets/f'study-57-page-{interior}.jpg',quality=91,optimize=True)

template=(root/'study-56-inheritance.html').read_text()
main='''<main>
<section class="detail-hero"><div class="wrap detail-hero-grid"><div class="detail-cover"><picture><source srcset="assets/study-57-cover.webp" type="image/webp"><img src="assets/study-57-cover.jpg" alt="The Eternal Purpose of God — Study 57 cover"></picture></div><div><div class="eyebrow">STUDY 57 · BIBLICAL DOCTRINE</div><h1>The Eternal Purpose of God</h1><p class="detail-subtitle">The Mystery Hidden in God, His Wisdom Displayed Through the Body, and All Things in Christ</p><p class="detail-kicker">What was purposed before the ages, and what is now made known?</p><p class="detail-copy">Ephesians says that God purposed in Christ before the ages, kept the Mystery hidden in Himself, and now makes His manifold wisdom known through the Church. Study 57 follows the relationship between purpose, disclosure, present witness, and the fullness of times.</p><p class="detail-copy">It reads Christ’s comprehensive headship alongside the distinct promises and recipients Scripture names. The study tests what Ephesians 3:10–11 actually says about the Church’s witness before heavenly authorities without adding an unstated command or governmental office.</p><div class="detail-buyline"><span class="detail-price">$5.99</span><span class="detail-format">Digital PDF · 16 Pages</span><span class="detail-button pending" aria-disabled="true">Checkout Coming Soon</span></div></div></div></section>
<section class="detail-section"><div class="wrap"><div class="eyebrow">ABOUT THIS STUDY</div><h2>Purpose Before the Ages, Wisdom Displayed Now</h2><p class="lead">God’s prior purpose and its historical disclosure are related, but they answer different questions. Ephesians 1 describes His will in Christ and the fullness of times; Ephesians 3 says the Mystery was hidden in God and now revealed through Paul, with wisdom made known through the Church. This study traces those claims in their contexts and marks the limits of what they establish about the ages to come.</p><p class="lead">Study 6 explains the content and timing of the Mystery’s revelation. Study 5 surveys the Body’s heavenly calling, Study 30 examines its present seating with Christ, and Study 56 asks what inheritance passages grant. Study 57 joins these questions around Ephesians 3:10–11: why does the revealed Body now display God’s wisdom, and how does that present witness accord with His eternal purpose? It does not turn the Church’s witness into an unstated commission over heavenly powers or transfer Israel’s covenants to the Body.</p>
<div class="study-distinction"><h3>How These Studies Relate</h3><p>Study 57 asks how God’s purpose in Christ relates to the Mystery’s disclosure, the Church’s present witness, and the future fullness. The neighboring studies supply the narrower claims this synthesis must respect.</p><p><a href="study-06-the-mystery-revealed-through-paul.html">Study 6 — The Mystery Revealed Through Paul</a> Establish what was hidden and disclosed through Paul; then use Study 57 to ask what Ephesians 3:10–11 says that disclosure now displays.</p><p><a href="study-05-the-heavenly-calling.html">Study 5 — The Heavenly Calling</a> Survey the Body’s blessings, identity, and hope before asking how this calling fits God’s larger purpose in Christ.</p><p><a href="study-30-seated-with-christ-in-heavenly-places.html">Study 30 — Seated With Christ in Heavenly Places</a> Test what Ephesians 2:6 establishes about present position before drawing conclusions about rule or jurisdiction from Ephesians 3:10.</p><p><a href="study-56-inheritance.html">Study 56 — Inheritance</a> Identify what inheritance texts actually promise before reading Ephesians 1:11 and Christ’s headship as a transfer of Israel’s named land grant.</p><p class="connection-guide-link"><a href="study-connections.html#study-57">Explore the full connection guide for Study 57 →</a></p></div>
<div class="eyebrow">WHAT YOU’LL STUDY</div><h2>Follow the Claims in Ephesians</h2><div class="study-points"><div class="study-point"><h3>Purpose and Disclosure</h3><p>Distinguish God’s intention before the ages from the Mystery’s historical revelation.</p></div><div class="study-point"><h3>The Fullness of Times</h3><p>Read Ephesians 1:9–10 as a claim about Christ without erasing named recipients elsewhere.</p></div><div class="study-point"><h3>The Mystery Hidden in God</h3><p>Follow Paul’s account of its disclosure and stewardship in Ephesians 3.</p></div><div class="study-point"><h3>Wisdom Made Known</h3><p>Identify the Church as the stated agent of witness to heavenly authorities.</p></div><div class="study-point"><h3>Christ’s Headship</h3><p>Keep His comprehensive supremacy and the distinct programs of Scripture in view.</p></div><div class="study-point"><h3>Limits of the Text</h3><p>Separate stated future display from detailed offices and timelines the passages leave unstated.</p></div></div>
<div class="eyebrow">KEY SCRIPTURES</div><h2>Read Purpose, Revelation, and Witness Together</h2><div class="scripture-grid"><div class="scripture-card"><h3>Ephesians 1:3–14</h3><p>God’s will, the fullness of times, and the Spirit’s earnest.</p></div><div class="scripture-card"><h3>Ephesians 1:15–23</h3><p>Christ exalted over all things and given as Head to the Church.</p></div><div class="scripture-card"><h3>Ephesians 2:1–10</h3><p>Grace, heavenly seating, and future display of His kindness.</p></div><div class="scripture-card"><h3>Ephesians 3:1–12</h3><p>The Mystery hidden in God, revealed through Paul, and wisdom made known.</p></div><div class="scripture-card"><h3>2 Timothy 1:8–12</h3><p>Grace given before the ages and manifested through Christ.</p></div><div class="scripture-card"><h3>Titus 1:1–3</h3><p>Promise before the ages and proclamation in due times.</p></div><div class="scripture-card"><h3>Colossians 1:24–29</h3><p>Paul’s stewardship and the Mystery now made manifest.</p></div><div class="scripture-card"><h3>Romans 11:25–29</h3><p>The named covenant recipients and God’s gifts and calling.</p></div></div>
<div class="eyebrow">FROM THE STUDY</div><h2>The Question Behind the Passage</h2><div class="excerpt"><blockquote>Intention and disclosure are not the same event.</blockquote><p>God’s purpose was prior; the Mystery was hidden until its appointed revelation. The study reads both statements without making prior intention equal prior public announcement.</p></div>
<div class="eyebrow">A LOOK INSIDE</div><h2>Preview the Study Before You Purchase</h2><p class="preview-instruction">Click any page to enlarge it for reading.</p><div class="preview-grid"><div class="preview-card"><a class="preview-image-link" data-preview-lightbox href="assets/study-57-page-3.jpg"><img src="assets/study-57-page-3.jpg" alt="Study 57 interior page 3 learning outcomes and study goal"></a><div class="page-no">Interior Page 3</div><h3>Learning Outcomes and Study Goal</h3><p>See the questions and guardrails that guide the study.</p></div><div class="preview-card"><a class="preview-image-link" data-preview-lightbox href="assets/study-57-page-6.jpg"><img src="assets/study-57-page-6.jpg" alt="Study 57 interior page 6 on the Church and manifold wisdom of God"></a><div class="page-no">Interior Page 6</div><h3>The Church and God’s Wisdom</h3><p>Read Paul’s stated claim in Ephesians 3:10–11.</p></div><div class="preview-card"><a class="preview-image-link" data-preview-lightbox href="assets/study-57-page-10.jpg"><img src="assets/study-57-page-10.jpg" alt="Study 57 interior page 10 on Christ’s headship and distinct programs"></a><div class="page-no">Interior Page 10</div><h3>Christ’s Headship and Distinct Programs</h3><p>See how the argument maintains the text’s limits.</p></div></div>
<div class="eyebrow">WHAT’S INCLUDED</div><h2>A Focused Study of Eternal Purpose</h2><div class="includes-grid"><div class="include-item"><h3>16-Page Digital PDF</h3><p>Approved cover and 15-page interior with a numbered table of contents.</p></div><div class="include-item"><h3>Nine Teaching Sections</h3><p>Move from prior purpose and disclosure to wisdom, headship, and future claims.</p></div><div class="include-item"><h3>Key Distinctions Table</h3><p>Compare what the texts establish with common conclusions they do not require.</p></div><div class="include-item"><h3>Interpretive Controls</h3><p>Keep audience, timing, stated agent, and the limits of each claim in view.</p></div><div class="include-item"><h3>Scripture-Tracing Exercise</h3><p>Record what was purposed, when it was disclosed, and what remains unstated.</p></div><div class="include-item"><h3>Teaching Outline and Further Study</h3><p>Use guided readings to test the argument against related studies.</p></div></div>
<div class="final-buy"><div><div class="eyebrow">STUDY 57 · DIGITAL STUDY</div><h2>The Eternal Purpose of God</h2><p>16-page digital PDF · For personal use</p></div><div class="final-offer"><div class="detail-price">$5.99</div><span class="detail-button pending" aria-disabled="true">Checkout Coming Soon</span></div></div><a class="back-link" href="digital-studies.html">← Back to All Digital Studies</a></div></section></main>'''
page=re.sub(r'<main>.*?</main>',main,template,flags=re.S)
page=page.replace('<title>Inheritance | Zay-Marie Press</title>','<title>The Eternal Purpose of God | Zay-Marie Press</title>')
page=re.sub(r'<meta name="description" content="[^"]*">','<meta name="description" content="Study 57 traces God’s eternal purpose in Christ, the Mystery revealed through Paul, and the Church’s present witness of His wisdom. Preview the 16-page study.">',page,count=1)
(root/'study-57-the-eternal-purpose-of-god.html').write_text(page)

catalog=root/'digital-studies.html';s=catalog.read_text()
card='<article class="study-card"><div class="study-type">Study 57 · Biblical Doctrine</div><h3><a href="study-57-the-eternal-purpose-of-god.html" style="color:inherit;text-decoration:none">The Eternal Purpose of God</a></h3><p>What does God’s purpose in Christ explain about the Mystery hidden in Him and now revealed through Paul? Follow Ephesians 1–3 through the Church’s present witness of divine wisdom, Christ’s headship, and the limits of future claims.</p><div class="study-meta"><span class="study-price">$5.99</span><a class="study-action" href="study-57-the-eternal-purpose-of-god.html" style="text-decoration:none">Preview Study</a></div></article>'
last=re.search(r'<article class="study-card"><div class="study-type">Study 56 · Biblical Doctrine</div>.*?</article>',s,re.S);assert last
s=s[:last.end()]+card+s[last.end():]
s=s.replace('data-count="studies">56','data-count="studies">57').replace('all 56 studies','all 57 studies').replace('56 Digital Studies','57 Digital Studies')
s=s.replace('Twelve-Study Collection','Thirteen-Study Collection').replace('<li>Study 56 — Inheritance</li>','<li>Study 56 — Inheritance</li><li>Study 57 — The Eternal Purpose of God</li>')
s=s.replace('and the distinct inheritance language addressed to Israel and the Body of Christ.','the distinct inheritance language addressed to Israel and the Body of Christ, and God’s eternal purpose in Christ as disclosed through Paul.')
s=s.replace('$58.99','$63.99').replace('$71.88 value','$77.87 value').replace('Save $12.89','Save $13.88')
catalog.write_text(s)

guide=root/'study-connections.html';s=guide.read_text()
s=s.replace('all 56 studies','all 57 studies').replace('all 56 Digital Studies','all 57 Digital Studies').replace('56 Digital Studies','57 Digital Studies').replace('Browse all 56 studies','Browse all 57 studies')
s=s.replace('THEME 3 · 10 STUDIES','THEME 3 · 11 STUDIES').replace('life now? · 10 studies','life now? · 11 studies')
entry='<details class="guide-entry" id="study-57"><summary><span class="entry-top">STUDY 57</span><span class="entry-title">The Eternal Purpose of God</span></summary><div class="entry-body"><p class="entry-intro"><strong>What this study answers.</strong> Study 57 traces God’s purpose in Christ before the ages, the Mystery’s later disclosure through Paul, and the Church’s present witness of manifold wisdom before heavenly authorities. It tests the scope and limits of these claims in Ephesians 1–3.</p><h4>How the connected studies help</h4><div class="guide-link"><a href="study-06-the-mystery-revealed-through-paul.html">Study 6 — The Mystery Revealed Through Paul</a><p>Establish the content and timing of the Mystery’s revelation first; then ask what Ephesians 3:10–11 says the disclosed Church now displays.</p></div><div class="guide-link"><a href="study-05-the-heavenly-calling.html">Study 5 — The Heavenly Calling</a><p>Survey the Body’s heavenly identity and blessings before connecting its calling to God’s larger purpose in Christ.</p></div><div class="guide-link"><a href="study-30-seated-with-christ-in-heavenly-places.html">Study 30 — Seated With Christ in Heavenly Places</a><p>Distinguish the Body’s stated present position in Ephesians 2:6 from claims about present rule or jurisdiction that Ephesians 3:10 does not itself command.</p></div><div class="guide-link"><a href="study-56-inheritance.html">Study 56 — Inheritance</a><p>Read the named heirs and objects in inheritance passages before treating Christ’s comprehensive headship as a transfer of Israel’s land grant.</p></div><div class="entry-footer"><a href="study-57-the-eternal-purpose-of-god.html">Preview Study 57 →</a><a href="#study-number-index">Study index ↑</a></div></div></details>'
doc=html.fromstring(s)
theme=doc.get_element_by_id('theme-life-and-standing-in-christ')
last_entry=theme.xpath('.//details[@class="guide-entry"]')[-1]
needle=html.tostring(last_entry,encoding='unicode')
assert needle in s
s=s.replace(needle,needle+entry)
index=re.search(r'(<div class="study-number-index".*?</div>)',s,re.S)
if index:
    s=s[:index.end()]+''+s[index.end():]
else:
    # Index uses a different wrapper: add alongside the final numbered link.
    m=list(re.finditer(r'<a[^>]*href="#study-56"[^>]*>.*?</a>',s,re.S));assert len(m)==1
    s=s[:m[0].end()]+'<a href="#study-57">57</a>'+s[m[0].end():]
guide.write_text(s)

generator=root/'generate_connections_pdf.py';g=generator.read_text().replace('==56','==57').replace('all 56 Digital Studies','all 57 Digital Studies');generator.write_text(g)
site=root/'sitemap.xml';s=site.read_text().replace('</urlset>','<url><loc>https://zaymariepress.com/study-57-the-eternal-purpose-of-god.html</loc></url></urlset>');site.write_text(s)
print('Study 57 site assets and pages prepared')
