from pathlib import Path
from lxml import html, etree

root = Path(__file__).parent
template = (root / 'study-54-justification.html').read_text()
head = template[:template.index('<main>')]
footer = template[template.index('</main>'):]
head = head.replace('Justification | Zay-Marie Press', 'Reconciled to God | Zay-Marie Press')
start = head.index('<meta name="description"')
end = head.index('>', start) + 1
head = head[:start] + '<meta name="description" content="Study 55 examines Paul’s doctrine of reconciliation: former enmity, peace with God through Christ, the appeal to be reconciled, and the entrusted ministry. Preview the study.">' + head[end:]

body = '''<main>
<section class="detail-hero"><div class="wrap detail-hero-grid"><div class="detail-cover"><picture><source srcset="assets/study-55-cover.webp" type="image/webp"><img src="assets/study-55-cover.jpg" alt="Reconciled to God — Study 55 cover"></picture></div><div><div class="eyebrow">STUDY 55 · DIGITAL STUDY</div><h1>Reconciled to God</h1><p class="detail-subtitle">Christ’s Work, Peace With God, and the Ministry of Reconciliation</p><p class="detail-kicker">A close reading of Romans 5, 2 Corinthians 5, Ephesians 2, and Colossians 1</p><p class="detail-copy">What does Paul mean when he says former enemies have peace with God? This study follows the order of God’s initiative in Christ, the accomplished work, the entrusted word, and the appeal to hearers. It distinguishes a reconciled standing from a passing feeling of closeness.</p><p class="detail-copy">The study also asks how Christ’s peace shapes one Body, how far Colossians’ “all things” language reaches, and why a broad reconciling purpose cannot by itself prove that every person has personally received salvation.</p><div class="detail-buyline"><span class="detail-price">$5.99</span><span class="detail-format">Digital PDF · 16 Pages</span><span class="detail-button pending" aria-disabled="true">Checkout Coming Soon</span></div></div></div></section>
<section class="detail-section"><div class="wrap"><div class="eyebrow">ABOUT THIS STUDY</div><h2>From Former Enmity to Peace With God</h2><p class="lead">Romans 5 locates peace after justification by faith and places it alongside hardship, not in place of it. Second Corinthians 5 names God’s initiative in Christ and the ministry and word entrusted to Paul and his coworkers. Ephesians 2 joins peace among former Jew and Gentile divisions to access to God in one Body. Colossians 1 speaks broadly of Christ’s reconciling purpose and then directly addresses people formerly alienated. Each passage contributes to the doctrine without surrendering its own audience and argument.</p><p class="lead">Readers who have studied Study 53 (Redemption) may wonder whether this study repeats its treatment of Christ’s blood, since both examine benefits secured through his death. Study 53 asks what bondage redemption answers and what price secures deliverance; Study 55 asks what becomes of former enemies in relation to God and why Paul announces an appeal to be reconciled. Readers of Study 54 (Justification) will encounter Romans 5:1 in both studies. Study 54 establishes the righteous verdict received by faith; this study follows the peace named in that verse and the received reconciliation of Romans 5:10–11. Study 37 (What Does Paul Mean by “New Creation”?) examines 2 Corinthians 5:17; this study follows verses 18–21 to distinguish God’s reconciling work, the entrusted message, and the hearer’s response. Study 52 (Sonship and Adoption) addresses standing and inheritance, while this study addresses enmity and peace. The question this study alone follows through all four principal passages is: how does God’s action in Christ establish peace, and how does Paul’s appeal relate to that accomplished work?</p>
<div class="study-distinction"><h3>How These Studies Relate</h3><p>Study 55 traces former enmity, God’s reconciling action in Christ, received peace, and the entrusted appeal. The related studies answer neighboring questions without making their terms interchangeable.</p><p><a href="study-53-redemption.html">Study 53 — Redemption</a> Examine the bondage answered and price paid through Christ’s blood; then return here to ask what relationship of peace that work establishes.</p><p><a href="study-54-justification.html">Study 54 — Justification</a> Study the righteous verdict received by faith; Romans 5 then shows how justified believers have peace with God.</p><p><a href="study-37-what-does-paul-mean-by-new-creation.html">Study 37 — What Does Paul Mean by “New Creation”?</a> Read 2 Corinthians 5:17 in its own argument before following verses 18–21 into God’s reconciling work and the appeal.</p><p><a href="study-52-sonship-and-adoption.html">Study 52 — Sonship and Adoption</a> Compare peace with God to the distinct standing and inheritance named by adoption.</p><p class="connection-guide-link"><a href="study-connections.html#study-55">Explore the full connection guide for Study 55 →</a></p></div>
<div class="eyebrow">WHAT YOU’LL STUDY</div><h2>Follow Paul’s Argument From Work to Appeal</h2><div class="study-points"><div class="study-point"><h3>Former Enmity and Present Peace</h3><p>Read Romans 5:1–11 for the former condition, Christ’s initiative, the benefit received, and confidence amid hardship.</p></div><div class="study-point"><h3>God’s Initiative in Christ</h3><p>Trace the verbs in 2 Corinthians 5:18–21: God acts, entrusts a word, and speaks through ambassadors.</p></div><div class="study-point"><h3>The Appeal to Be Reconciled</h3><p>Distinguish Christ’s completed work from its proclamation and a hearer’s reception.</p></div><div class="study-point"><h3>Peace in One Body</h3><p>Follow Ephesians 2:11–18 without transferring Israel’s covenant identity to the Body.</p></div><div class="study-point"><h3>The Reach of “All Things”</h3><p>Honor Colossians 1:19–23’s breadth while reading its direct address and exhortation.</p></div><div class="study-point"><h3>Ministry and Conduct</h3><p>Explain what ambassadors announce and why the believer’s pursuit of interpersonal peace follows grace.</p></div></div>
<div class="eyebrow">KEY SCRIPTURES</div><h2>Read the Passages in Their Own Contexts</h2><div class="scripture-grid"><div class="scripture-card"><h3>Romans 5:1–11</h3><p>Peace with God, former enmity, and reconciliation received through Christ.</p></div><div class="scripture-card"><h3>2 Corinthians 5:14–21</h3><p>God’s action in Christ, the entrusted word, the ambassador, and the appeal.</p></div><div class="scripture-card"><h3>Ephesians 2:11–18</h3><p>Christ’s peace among former divisions and access to the Father in one Body.</p></div><div class="scripture-card"><h3>Colossians 1:19–23</h3><p>“All things,” the formerly alienated “you,” and the stated gospel exhortation.</p></div><div class="scripture-card"><h3>Romans 11:11–15</h3><p>A related word in an Israel-specific argument that must be read on its own terms.</p></div><div class="scripture-card"><h3>Romans 12:18</h3><p>The fitting pursuit of peace with others, distinct from Christ’s saving work.</p></div></div>
<div class="eyebrow">FROM THE STUDY</div><h2>A Distinction That Guides the Whole Study</h2><div class="excerpt"><blockquote>God acts in Christ; Paul announces the work and delivers the appeal.</blockquote><p>Reconciliation is not a mood the believer manufactures, nor can the hearer’s response be exchanged for Christ’s reconciling work. The study asks readers to follow the movement of each passage before drawing a doctrinal conclusion.</p></div>
<div class="eyebrow">A LOOK INSIDE</div><h2>Preview the Study Before You Purchase</h2><p class="preview-instruction">Click any page to enlarge it for reading.</p><div class="preview-grid"><div class="preview-card"><a class="preview-image-link" data-preview-lightbox href="assets/study-55-page-3.jpg"><img src="assets/study-55-page-3.jpg" alt="Study 55 table of contents"></a><div class="page-no">Page 3</div><h3>Table of Contents</h3><p>See the complete study structure and its passage sequence.</p></div><div class="preview-card"><a class="preview-image-link" data-preview-lightbox href="assets/study-55-page-4.jpg"><img src="assets/study-55-page-4.jpg" alt="Study 55 learning outcomes and study outline"></a><div class="page-no">Page 4</div><h3>Learning Outcomes and Outline</h3><p>Read the study goal and the questions guiding each section.</p></div><div class="preview-card"><a class="preview-image-link" data-preview-lightbox href="assets/study-55-page-8.jpg"><img src="assets/study-55-page-8.jpg" alt="Study 55 passage analysis of the appeal to be reconciled"></a><div class="page-no">Page 8</div><h3>The Appeal to Be Reconciled</h3><p>See how the study distinguishes the work, message, and response.</p></div><div class="preview-card"><a class="preview-image-link" data-preview-lightbox href="assets/study-55-page-14.jpg"><img src="assets/study-55-page-14.jpg" alt="Study 55 summary and key distinctions"></a><div class="page-no">Page 14</div><h3>Summary and Key Distinctions</h3><p>Review the contributions and boundaries of the four principal passages.</p></div></div>
<div class="eyebrow">WHAT’S INCLUDED</div><h2>A Focused Study for<br>Reading and Teaching</h2><div class="includes-grid"><div class="include-item"><h3>16-Page Digital PDF</h3><p>The approved cover and 15-page interior with a numbered title page and table of contents.</p></div><div class="include-item"><h3>Eight Teaching Sections</h3><p>Move from the question reconciliation answers through Romans, Corinthians, Ephesians, and Colossians to ministry and application.</p></div><div class="include-item"><h3>Key Distinctions</h3><p>Keep work and message, scope and reception, and reconciliation and neighboring benefits distinct.</p></div><div class="include-item"><h3>Scripture-Tracing Exercise</h3><p>Record audience, former condition, divine action, and warranted conclusion in each passage.</p></div><div class="include-item"><h3>Teaching Outline</h3><p>Use a six-part framework for presenting the doctrine clearly.</p></div><div class="include-item"><h3>Guided Further Study</h3><p>Investigate peace, ministry, corporate unity, and the scope of the passages with directed questions.</p></div></div>
<div class="final-buy"><div><div class="eyebrow">STUDY 55 · DIGITAL STUDY</div><h2>Reconciled to God</h2><p>16-page digital PDF · For personal use</p></div><div class="final-offer"><div class="detail-price">$5.99</div><span class="detail-button pending" aria-disabled="true">Checkout Coming Soon</span></div></div><a class="back-link" href="digital-studies.html">← Back to All Digital Studies</a></div></section></main>'''

(root / 'study-55-reconciled-to-god.html').write_text(head + body + footer.replace('</main>','',1))
