(() => {
  const root = document.querySelector('#resource-library');
  if (!root) return;

  const table = (headers, rows) => `<div class="rl-table-wrap"><table class="rl-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const principle = text => `<div class="rl-principle"><strong>Key Principle</strong><p>${text}</p></div>`;
  const refs = text => `<p><strong>Suggested Scripture:</strong> ${text}</p>`;
  const book = (title, copy, href) => `<div class="rl-book-link"><strong>${title}</strong><p>${copy}</p><a href="${href}">Learn more</a></div>`;

  const resources = [
    {id:1,title:'Reading Scripture Literally',subtitle:'Grammar, Context, Audience, and Divine Program',category:'Interpretation',tags:['Hermeneutics','Context','Right Division'],desc:'Five foundations for reading Scripture according to its normal meaning while respecting audience, context, and divine program.',content:()=>`
      <p>Literal interpretation respects grammar, literary form, historical setting, audience, revelatory context, and divine program. It seeks the meaning God actually communicated rather than replacing that meaning with a later theological idea.</p>
      <h3>Five Foundations</h3><ol><li><strong>Normal grammatical meaning.</strong> Read words and sentences according to their ordinary grammatical sense while recognizing genuine figures of speech and literary forms.</li><li><strong>Historical and literary context.</strong> Read a passage within its book, historical setting, and surrounding argument.</li><li><strong>Original audience.</strong> Identify whom the passage addresses before deciding how it applies to someone else.</li><li><strong>Divine program in view.</strong> Preserve the distinction between the Prophecy Program for Israel and the Mystery Program for the Body of Christ.</li><li><strong>Progressive revelation without rewriting earlier revelation.</strong> Prophecy was revealed in seed form in the Law and progressively expanded through the prophets. The Mystery was previously hidden and unrevealed until revealed through Paul. Later revelation may add truth without changing what earlier revelation originally meant.</li></ol>
      <div class="rl-note"><strong>A Necessary Distinction</strong><p>Literal interpretation does not mean that every biblical command is directly addressed to every believer. A passage can be literally true, historically accurate, divinely inspired, and spiritually instructive without being the governing doctrinal instruction for the Body of Christ.</p></div>
      <h3>A Simple Example</h3><p>When Israel was commanded to observe the Passover, literal interpretation recognizes a real command given to a real covenant people in a real historical setting. The command should not be allegorized away, nor should it automatically be imposed upon the Body of Christ simply because it appears in inspired Scripture.</p>
      <h3>What Literal Interpretation Does Not Mean</h3><ul><li>It does not deny figures of speech or symbolism.</li><li>It does not make every command directly applicable to every audience.</li><li>It does not transfer Israel's promises to the Body of Christ.</li><li>It does not collapse Prophecy and Mystery into one program.</li></ul>
      ${principle('Right division does not eliminate application; it establishes the proper basis for application.')}`},
    {id:2,title:'Hermeneutics Comparison Chart',subtitle:'Reading Scripture Without Flattening Its Distinctions',category:'Interpretation',tags:['Hermeneutics','Audience','Progressive Revelation'],desc:'A comparison of grammatical-historical right division with approaches that flatten biblical audiences and programs.',content:()=>`
      <p>The Acts Overlap Framework uses a grammatical-historical approach that preserves biblical distinctions of audience, revelation, and divine program.</p>
      ${table(['Interpretive Question','Grammatical-Historical / Right-Division Approach','Flattened or Non-Distinguishing Approach'],[
      ['Meaning','Seeks the plain sense of the text according to grammar, history, and literary context.','May allow later theological systems to control the original meaning.'],
      ['Audience','Identifies whom God is addressing before determining doctrinal application.','Tends to treat biblical instructions as though addressed equally to every believer.'],
      ['Context','Interprets passages within their immediate and broader biblical setting.','May isolate passages from their historical or programmatic setting.'],
      ['Progressive Revelation','Allows later revelation to add truth without rewriting what earlier revelation originally meant.','May reinterpret earlier revelation so extensively that its original meaning is displaced.'],
      ['Israel','Preserves Israel’s national identity and the promises God made to Israel.','May transfer Israel’s promises or identity to another people.'],
      ['Body of Christ','Recognizes the Body as a distinct people belonging to the Mystery Program.','May merge the Body with Israel or place it under Israel’s governing program.'],
      ['Prophecy','Recognizes a program revealed in seed form in the Law and progressively expanded through the prophets.','May treat prophetic revelation as merely symbolic material ultimately describing the Church.'],
      ['Mystery','Recognizes previously hidden truth revealed through Paul.','May read the Mystery backward into revelation in which Scripture says it had been hidden.'],
      ['Acts','Allows Prophecy and Mystery to operate concurrently during Acts 9–28.','May force Acts into a simple replacement or sequential-transition model.'],
      ['Application','Distinguishes direct doctrinal governance from legitimate spiritual instruction and application.','May assume that application requires every passage to govern the same audience directly.']])}
      ${principle('Sound interpretation asks not only, “What does this passage say?” but also, “To whom was it revealed, within what context, and under what divine program?”')}<p><strong>Right division does not eliminate application; it establishes the proper basis for application.</strong></p>`},
    {id:3,title:'New Believer Starter Pack',subtitle:'A Simple Pauline Foundation for Beginning the Christian Life',category:'Discipleship',tags:['New Believer','Gospel','Identity'],desc:'A practical starting point for understanding the gospel, your identity in Christ, Scripture, prayer, growth, and fellowship.',content:()=>`
      <p>You have trusted Christ. What should you understand and do next? Begin with a simple Pauline foundation without feeling that you must master the entire Acts Overlap framework at once.</p>
      <h3>1. Begin with the Gospel</h3><p>Salvation is God's gift of grace received through faith in the finished work of Christ. Christ died for our sins, was buried, and rose again. Acceptance before God is not earned through religious works, ceremonies, or personal merit.</p>${refs('1 Corinthians 15:1–4; Ephesians 2:8–9; Romans 3:24–28')}
      <h3>2. Understand Your New Identity</h3><p>In Christ you possess a new identity and are a member of the Body of Christ. Christian growth begins with <strong>position before performance</strong>: learn what God has made you in Christ before treating Christian conduct as a means of earning that position.</p>${refs('2 Corinthians 5:17; Ephesians 1:3–7; Colossians 2:10; 1 Corinthians 12:13')}
      <h3>3. Learn Where Your Governing Doctrine Is Found</h3><div class="rl-note"><strong>All Scripture Is God's Word, but Not Every Passage Is Addressed to the Same Audience</strong><p>The entire Bible is inspired and profitable for learning. Yet God did not give every promise, command, or instruction to the same people under the same divine program.</p><p>For the Body of Christ, <strong>Romans through Philemon provide the governing doctrinal revelation for our identity, calling, walk, and hope</strong>. This does not make the rest of Scripture unimportant. It helps us read the entire Bible according to the distinctions God placed within it.</p></div>
      <h3>4. Start Reading Scripture</h3><p>A helpful Pauline reading path is <strong>Romans → Ephesians → Philippians → Colossians → 1 &amp; 2 Thessalonians</strong>. Romans is foundational and substantial; Ephesians can also provide a shorter introduction to identity and position in Christ before returning to Romans. Read the whole Bible while learning to recognize audience, context, and divine program.</p>
      <h3>5. Learn to Pray</h3><p>Prayer includes thanksgiving, dependence, and confidence in God. Let Scripture shape your desires and prayers.</p>${refs('Philippians 4:6–7; Colossians 4:2; Ephesians 3:14–21')}
      <h3>6. Grow in Grace and Understanding</h3><p>Christian growth is not accomplished by placing yourself back under Israel's Law program. Growth comes as the truth of God's Word renews your thinking and produces a walk consistent with your position in Christ.</p>${refs('Romans 12:1–2; Ephesians 4:1; Colossians 2:6–7')}
      <h3>7. Connect with Other Believers</h3><p>Seek fellowship with believers who honor the authority of Scripture, proclaim salvation by grace through faith in Christ, and take seriously the importance of understanding Scripture according to its proper audience and context.</p>
      <h3>What Should I Learn Next?</h3><p>Begin with the gospel and your identity in Christ. Then learn audience and context, the Prophecy/Mystery distinction, and finally the concurrent operation of the two programs during Acts 9–28.</p>`},
    {id:4,title:'Doctrines Every Christian Should Know',subtitle:'Universal Truths and Essential Truths for the Body of Christ',category:'Doctrine',tags:['Universal Truth','Body of Christ','Doctrine'],desc:'A concise doctrinal foundation distinguishing truths that are universal from truths governing the Body of Christ.',content:()=>`
      <p>Scripture contains truths that are universal and truths that must be understood according to their particular divine program. Right division requires recognizing both.</p><p><strong>Universal Truths</strong> remain true across programmatic boundaries. <strong>Program-Specific Truths</strong> concern particular audiences, callings, promises, instructions, or divine purposes.</p>${principle('Right division does not divide what God has made universal, and it does not universalize what God has made program-specific.')}
      <h3>Part One — Universal Truths</h3>
      ${[['God','There is one true God, eternally existing as Father, Son, and Holy Spirit. God is holy, righteous, sovereign, faithful, and unchanging in His character.','Deuteronomy 6:4; Matthew 28:19; 2 Corinthians 13:14'],['Scripture','The Scriptures are inspired by God and constitute His authoritative written revelation. Because Scripture is God’s Word, its distinctions must be respected rather than erased.','2 Timothy 3:16–17; 2 Peter 1:20–21'],['Jesus Christ','Jesus Christ is fully God and truly man. He entered human history, died, was buried, rose bodily from the dead, and now lives exalted at the right hand of God.','John 1:1, 14; Philippians 2:5–11; 1 Corinthians 15:3–4'],['Humanity and Sin','Humanity is fallen and sinful and cannot establish righteousness before God through human merit or religious works.','Romans 3:9–23; 5:12'],['The Death and Resurrection of Christ','Christ’s death and bodily resurrection are objective historical realities central to God’s redemptive purpose. The fullness of what God later reveals concerning the believer’s identification, position, and standing in Christ must be understood within its proper revelatory context.','1 Corinthians 15:3–4'],['God’s Faithfulness','God remains faithful to His Word and purposes. Promises made to a particular people do not need to be reassigned to another people in order for those promises to be fulfilled.','Romans 11:25–29']].map(x=>`<h4>${x[0]}</h4><p>${x[1]}</p>${refs(x[2])}`).join('')}
      <h3>Part Two — Essential Truths for the Body of Christ</h3>
      ${[['Salvation by Grace Through Faith','Under God’s present administration, salvation is received by grace through faith apart from works. The believer rests in the finished work of Christ rather than religious performance as the basis of acceptance before God.','Ephesians 2:8–9; Romans 3:24–28; Titus 3:5'],['The Gospel','The gospel proclaimed through Paul’s ministry centers upon Christ’s death for our sins, His burial, and His resurrection.','1 Corinthians 15:1–4'],['The Body of Christ','Believing Jews and Gentiles are joined in one Body without national distinction or covenantal hierarchy.','1 Corinthians 12:13; Ephesians 2:14–16; 3:6'],['The Believer’s Position in Christ','Members of the Body of Christ possess a heavenly position and spiritual blessings in Christ. Christian living proceeds from this God-given position rather than being the means by which that position is earned.','Ephesians 1:3; 2:4–6; Colossians 2:10'],['The Believer and the Law','The Body of Christ is not governed by Israel’s Mosaic Law covenant as its rule of standing before God. Christian conduct flows from grace and the believer’s identity in Christ.','Romans 6:14; 7:4–6; Galatians 5:18'],['The Believer’s Walk','Grace does not eliminate godly conduct. The believer is called to walk consistently with the position already received in Christ.','Romans 12:1–2; Ephesians 4:1; 5:1–2; Colossians 2:6–7'],['The Believer’s Hope','The Body of Christ possesses a heavenly hope centered in Christ and the gathering of believers to Him.','1 Thessalonians 4:13–18; Philippians 3:20–21']].map(x=>`<h4>${x[0]}</h4><p>${x[1]}</p>${refs(x[2])}`).join('')}
      <div class="rl-note"><strong>Do Not Confuse Universal with Program-Specific</strong><p>The deity of Christ does not become a “Prophecy truth” simply because it appears in the Gospels. Neither does every command spoken by Christ during His earthly ministry automatically become governing instruction for the Body of Christ.</p><p><strong>Where a truth appears in Scripture and whom a particular instruction governs are related questions—but they are not the same question.</strong></p></div>
      <h3>Truth Must Be Believed—and Rightly Placed</h3><p>Faithfulness to Scripture requires more than affirming true statements. It also requires understanding those truths according to the audience, revelatory setting, and divine program God has given them.</p>${book('Go Deeper with The Full Framework','Explore the complete theological architecture of the Acts Overlap Model.','full-framework.html')}`},
    {id:5,title:'Bible Timelines',subtitle:'Biblical Eras and the Distinctive Acts Overlap',category:'Timelines & Charts',tags:['Timeline','Acts 9–28','Chronology'],desc:'A high-level biblical chronology that distinguishes ordinary historical succession from programmatic concurrency during Acts.',content:()=>`
      <p>Biblical history contains genuine chronological succession, but Acts 9–28 cannot be represented accurately as one program simply ending before another begins.</p>
      <h3>High-Level Biblical Eras</h3><ol><li><strong>Creation / Innocence</strong> — Creation, humanity’s original state, and the entrance of sin.</li><li><strong>Conscience</strong> — Humanity functioning with the knowledge of good and evil following the Fall.</li><li><strong>Human Government</strong> — Post-Flood governmental responsibility beginning with Noah.</li><li><strong>Promise</strong> — God’s promises associated particularly with Abraham and his descendants.</li><li><strong>Law and Israel’s Prophetic Program</strong> — The Law is given to Israel. The Prophecy Program is revealed in seed form in the Law and progressively expanded through the prophets.</li><li><strong>Earthly Ministry of Christ</strong> — Christ ministers primarily to Israel within the Prophecy Program, proclaiming Israel’s Kingdom message.</li><li><strong>Early Acts — Prophecy Continues</strong> — Israel’s prophetic program remains in operation and the kingdom witness to national Israel continues.</li></ol>
      <h3>Acts 9–28 — The Acts Overlap</h3><img class="rl-timeline-image" src="assets/bible-timelines-acts-overlap.png" alt="Acts 9–28 chronology: Prophecy begins before Acts 9, Mystery begins independently at Acts 9, both operate concurrently while remaining separate through Acts 28, Prophecy is suspended at Acts 28, and Mystery continues beyond Acts 28" onerror="this.style.display='none';this.nextElementSibling.hidden=false"><div class="rl-image-fallback" hidden><strong>Chronology:</strong> Prophecy is already operating before Acts 9. Mystery begins independently at Acts 9. Both programs operate concurrently and remain separate through Acts 9–28. Prophecy is suspended at Acts 28; Mystery continues beyond Acts 28.</div>
      <p>During Acts 9–28, the Prophecy Program for Israel and the Mystery Program for the Body of Christ operate concurrently. Neither program develops out of the other, and neither loses its distinct identity during the overlap.</p>
      <h3>Acts 28 — Prophecy Suspended</h3><p>Israel’s Prophecy Program reaches its suspension boundary. Acts 28 does not mark the beginning of the Mystery Program.</p><h3>Beyond Acts 28 — Mystery Continues</h3><p>The Mystery Program, already operating since Acts 9, continues as God’s present administration for the Body of Christ.</p><h3>Future Prophetic Fulfillment</h3><p>Israel’s prophetic program resumes according to God’s purposes, culminating in national restoration, Christ’s earthly Kingdom, fulfillment of Israel’s covenant promises, and Israel’s inheritance in the New Earth.</p>
      <div class="rl-note"><strong>Why Does the Timeline Change at Acts 9?</strong><p>Most historical periods can be displayed sequentially. Acts 9–28 cannot be represented accurately by a simple sequence because two distinct divine programs operate concurrently during the same historical period.</p></div>${principle('Chronology determines when events occur; revelation determines which program they belong to.')}`},
    {id:6,title:'Israel and the Body of Christ',subtitle:'Identity Comparison Chart — Two Distinct Programs. One Divinely Coordinated Overlap.',category:'Doctrine',tags:['Israel','Body of Christ','Identity'],desc:'A focused comparison of the two programmatic peoples, their identities, callings, revelatory foundations, and purposes.',content:()=>`
      ${table(['Category','Prophecy Program — Israel','Mystery Program — Body of Christ'],[
      ['Program','God’s revealed, covenantal program for national Israel','God’s previously hidden, non-covenantal program for the Body of Christ'],['Revelatory Character','Revealed in seed form in the Law and progressively expanded through the prophets','Unspoken, unrevealed, and kept hidden until revealed through Paul'],['Identity','National Israel as a covenant people','One Body composed of believing Jews and Gentiles with no national distinction'],['Calling','Earthly, national, kingdom-centered','Heavenly, spiritual, Body-centered'],['Covenantal Character','Directly tied to Abrahamic, Davidic, and New Covenant promises','Not tied to Israel’s covenants; operates outside covenant structure'],['Kingdom Orientation','Earthly kingdom centered in Jerusalem','Heavenly position and destiny in Christ'],['Program Messenger','Prophets and apostles of Israel’s program','Paul as the divinely appointed apostle and steward through whom the Mystery is revealed'],['Primary Doctrinal Corpus','Scriptures governing Israel’s prophetic program and covenant promises','Romans–Philemon as the governing revelation for the Body of Christ'],['Acts Relationship','Continues through Acts; suspended at Acts 28','Begins at Acts 9; operates concurrently through Acts 28; continues beyond'],['Ultimate Purpose','Fulfillment of God’s promises to Israel','Fulfillment of God’s previously hidden purpose for the Body of Christ']])}
      ${principle('Israel and the Body of Christ must not be distinguished merely as two groups of believers. They belong to two distinct divine programs—Prophecy and Mystery—with different revelatory foundations, identities, callings, and purposes. During Acts 9–28, those programs operate concurrently without merging.')}${book('Go Deeper with The Full Framework','Explore the full theological architecture behind these distinctions.','full-framework.html')}`},
    {id:7,title:'Paul’s Epistles Timeline',subtitle:'Chronology, Ministry Setting, and Pauline Doctrinal Authority',category:'Timelines & Charts',tags:['Paul','Epistles','Chronology'],desc:'An approximate historical timeline of Paul’s epistles that keeps chronology distinct from doctrinal authority.',content:()=>`
      ${principle('Chronology tells us when an epistle was written. Revelation tells us what divine program and doctrinal authority it belongs to.')}
      <p>Dates are approximate, and the dating of some Pauline letters—especially Galatians—is disputed. Romans–Philemon constitute the Pauline doctrinal corpus regardless of disputes over the precise date of individual epistles.</p>
      <h3>Early Pauline Ministry — During the Acts Overlap</h3><ul><li><strong>Galatians</strong> — approximate/disputed date</li><li><strong>1 Thessalonians</strong> — approximately AD 50–51</li><li><strong>2 Thessalonians</strong> — approximately AD 51–52</li></ul><p>These letters were written while the Prophecy Program for Israel and the Mystery Program for the Body of Christ were operating concurrently. Their early date does not make them part of Israel’s Prophecy Program. They are Pauline epistles addressed within the revelatory and doctrinal framework of the Mystery Program.</p>
      <h3>Later Acts-Period Pauline Ministry</h3><ul><li><strong>1 Corinthians</strong> — approximately AD 54–55</li><li><strong>2 Corinthians</strong> — approximately AD 55–56</li><li><strong>Romans</strong> — approximately AD 56–57</li></ul><p>Paul’s Acts-period epistles provide substantial doctrine concerning the gospel, justification, the Body of Christ, spiritual life, Christian conduct, and the believer’s relationship to Israel and the Law while the two divine programs remain concurrently operative.</p>
      <h3>Imprisonment and Later Pauline Ministry</h3><p>Ephesians, Philippians, Colossians, Philemon, 1 Timothy, Titus, and 2 Timothy belong to Paul’s imprisonment and later ministry. Paul’s imprisonment and later epistles continue the Mystery revelation already operative during Acts, addressing the Body’s identity, heavenly position, walk, ministry order, perseverance, and related doctrinal concerns.</p><div class="rl-note"><strong>Post-Acts continuation is not post-Acts origin.</strong><p>The Mystery Program begins with Paul’s calling and commission in Acts 9, operates concurrently with Prophecy through Acts 28, and continues beyond Acts 28.</p></div>`},
    {id:8,title:'Acts Overlap Summary Sheet',subtitle:'A Concise Guide to the Concurrent Operation of the Prophecy and Mystery Programs',category:'Timelines & Charts',tags:['Acts 9–28','Prophecy','Mystery'],desc:'A concise map of the Acts Overlap: two distinct programs operating concurrently without merging.',content:()=>`
      <p>The Book of Acts records a unique period in which two distinct divine programs operate concurrently. The <strong>Prophecy Program for national Israel</strong>, already in operation before Acts begins, continues alongside the <strong>Mystery Program for the Body of Christ</strong>, which begins with Paul’s calling and commission in Acts 9.</p><p>From Acts 9 through Acts 28, these programs remain distinct while operating concurrently within the same historical period. At Acts 28, the Prophecy Program is suspended; the Mystery Program continues beyond that boundary.</p>
      <div class="rl-program-grid"><div class="rl-program prophecy"><h4>Prophecy Program</h4><p>The Prophecy Program concerns God’s revealed purposes for national Israel. It was revealed in seed form in the Law and progressively expanded through the prophets. Its character is national, covenantal, earthly, and kingdom-centered.</p></div><div class="rl-program mystery"><h4>Mystery Program</h4><p>The Mystery Program concerns God’s previously hidden purpose for the Body of Christ. It was unspoken and unrevealed in prior ages until revealed through Paul. Its character is non-national, non-covenantal, and associated with the heavenly calling and position of the Body of Christ.</p></div></div>
      <h3>What “Overlap” Means</h3><p><strong>Overlap does not mean transition.</strong> The Acts Overlap is not the gradual transformation of Israel’s Prophecy Program into the Mystery Program. Neither program develops out of the other.</p><p>During Acts 9–28, both programs operate within the same historical period while retaining their distinct audiences, revelatory foundations, purposes, and program markers.</p>${principle('Concurrency describes their historical relationship; distinction describes their theological relationship.')}
      <h3>Four Boundaries to Remember</h3><ol><li><strong>Prophecy does not begin in Acts.</strong> It is already operating before Acts 9.</li><li><strong>Mystery does not begin at Acts 28.</strong> It begins with Paul’s calling and commission in Acts 9.</li><li><strong>Acts 9–28 is concurrent operation.</strong> Continuing prophetic activity does not mean the Mystery has not begun, and Mystery revelation does not mean Prophecy has already been suspended.</li><li><strong>Acts 28 is a boundary for Prophecy, not the origin of Mystery.</strong> Prophecy reaches its suspension boundary while Mystery continues.</li></ol>
      <h3>Reading Acts During the Overlap</h3><p>Because two programs operate concurrently during Acts 9–28, chronological location alone does not determine which program governs a particular passage. Readers must pay attention to the speaker, audience, context, divine program, and recognizable program markers.</p><p>A passage involving Paul is not automatically Mystery simply because Paul appears in it. Likewise, the continued presence of Israel, kingdom proclamation, signs, or other prophetic features does not mean the Mystery Program has not yet begun.</p>
      <h3>What Acts 28 Does—and Does Not—Mean</h3><p><strong>Acts 28 marks the suspension of the Prophecy Program for national Israel.</strong> It does not mark the beginning of the Mystery Program, the first appearance of the Body of Christ, or the point at which Paul finally receives Mystery truth.</p>
      <div class="rl-principle"><strong>THE ACTS OVERLAP PRINCIPLE</strong><p>From Acts 9 through Acts 28, the Prophecy Program for national Israel and the Mystery Program for the Body of Christ operate concurrently without merging. Prophecy is suspended at Acts 28; Mystery continues beyond.</p></div>
      ${book('Go Deeper with The Diagnostic Manual — COMING SOON','Recognizing that two programs operate concurrently is the beginning. The Diagnostic Manual develops the complete method for identifying program, revelatory basis, program markers, chronology, and proper doctrinal application throughout Acts.','diagnostic-manual.html')}`},
    {id:9,title:'Prophecy and Mystery',subtitle:'Two Distinct Divine Programs — Concurrent During the Acts Overlap',category:'Doctrine',tags:['Prophecy','Mystery','Programs'],desc:'A direct comparison of the two divine programs and their distinct revelatory foundations, audiences, callings, and purposes.',content:()=>`
      <p>Scripture reveals two distinct divine programs that must not be confused: the <strong>Prophecy Program for national Israel, revealed in seed form in the Law and progressively expanded through the prophets</strong>, and the <strong>Mystery Program for the Body of Christ, previously hidden and later revealed through Paul</strong>.</p><p>During Acts 9–28, these programs operate concurrently. Their historical overlap does not erase their distinct revelatory character, audiences, callings, or purposes.</p>
      ${table(['Category','Prophecy Program','Mystery Program'],[
      ['Revelatory Origin','Revealed in seed form in the Law and progressively expanded through the prophets','Previously unspoken, unrevealed, and hidden until revealed through Paul'],['Primary Audience','National Israel','Body of Christ—believing Jews and Gentiles without national distinction'],['Program Character','National, covenantal, and prophetic','Non-national, non-covenantal, and previously hidden'],['Sphere of Calling','Earthly and kingdom-centered','Heavenly and Body-centered'],['Covenant Relationship','Grounded in God’s covenant promises to Israel','Operates outside Israel’s covenant structure'],['Kingdom Orientation','Israel’s promised earthly kingdom centered in Jerusalem','Heavenly position and destiny in Christ'],['Program Messenger','Prophets and apostles associated with Israel’s prophetic program','Paul as the divinely appointed apostle and steward through whom the Mystery is revealed'],['Program Markers','Israel, covenants, kingdom proclamation, prophetic fulfillment, and signs associated with Israel’s program','One Body, equal standing of Jew and Gentile, heavenly position, and truth distinctive to the Mystery'],['Beginning in Relation to Acts','Already operating when Acts begins','Begins with Paul’s calling and commission in Acts 9'],['Acts 9–28','Continues operating','Operates concurrently with Prophecy'],['Acts 28 Boundary','Suspended at Acts 28','Does not begin at Acts 28; continues beyond it'],['Ultimate Purpose','Fulfillment of God’s revealed promises concerning Israel','Fulfillment of God’s previously hidden purpose for the Body of Christ']])}
      ${principle('Prophecy and Mystery are not successive labels for the same divine program. They are distinct programs with distinct revelatory foundations and purposes. During Acts 9–28, both operate concurrently without merging or becoming one another.')}${book('Go Deeper with The Full Framework','Explore the complete theological architecture of the Acts Overlap Model.','full-framework.html')}`},
    {id:10,title:'7-Day Devotional: Who You Are in Christ',subtitle:'A Week of Pauline Truth for Identity, Position, Walk, and Hope',category:'Devotional',tags:['Identity','In Christ','Devotional'],desc:'Seven short devotional readings focused on the believer’s identity and position in Christ.',content:()=>`<p>This seven-day devotional lets the practical fruit of the framework come forward: your identity and position in Christ. Select a day below.</p><div class="rl-days" role="tablist">${[1,2,3,4,5,6,7].map(n=>`<button class="rl-day${n===1?' active':''}" data-day="${n}" role="tab" aria-selected="${n===1}">Day ${n}</button>`).join('')}</div><div class="rl-devotional" aria-live="polite"></div>`},
    {id:11,title:'Rightly Dividing Scripture',subtitle:'Foundational Questions for Reading the Bible in Its Proper Context',category:'Interpretation',tags:['Right Division','Study','Context'],desc:'Six foundational questions for recognizing audience, context, chronology, and divine program without replacing the complete diagnostic method.',content:()=>`
      <p>Rightly dividing Scripture begins by allowing each passage to retain its own audience, context, and divine purpose. Not every biblical instruction is addressed to the same people or governed by the same divine program.</p><p>These foundational questions can help the reader recognize important distinctions before drawing doctrinal conclusions.</p>
      <h3>Foundational Right-Division Questions</h3><ol><li><strong>Who is speaking or writing?</strong> Identify the human speaker or writer and the setting.</li><li><strong>Who is being addressed?</strong> Determine whether the audience is Israel, the Body of Christ, a particular group, or individuals. Do not assume every passage is addressed directly to the same audience.</li><li><strong>What is the immediate biblical context?</strong> Consider surrounding verses, the book’s purpose, and historical circumstances.</li><li><strong>Which divine program is in view?</strong> Is the passage operating within the Prophecy Program for Israel or the Mystery Program for the Body of Christ? Do not merge the programs.</li><li><strong>Where does the passage fall in biblical and Acts chronology?</strong> Prophecy is already operating before Acts 9; Mystery begins at Acts 9; both operate concurrently Acts 9–28; Prophecy is suspended at Acts 28; Mystery continues.</li><li><strong>Am I preserving distinctions Scripture establishes?</strong> Do not make Israel into the Body, place the Body under Israel’s program, or merge the concurrent programs of Acts.</li></ol>
      <div class="rl-note"><strong>A Beginning, Not the Entire Method</strong><p>These questions provide a foundation for reading Scripture according to its audience, context, chronology, and divine program. Some passages—particularly during the Acts 9–28 overlap—require a more disciplined analysis.</p></div>
      ${book('Go Deeper with The Diagnostic Manual — COMING SOON','The Diagnostic Manual develops the complete method for identifying program, revelatory basis, program markers, chronology, and proper doctrinal application throughout Acts.','diagnostic-manual.html')}`}
  ];

  const devotionalDays = {
    1:['You Are in Christ','The believer’s fundamental identity is no longer determined by the old life but by his or her position in Christ.','2 Corinthians 5:17; Ephesians 1:3–7','Thank God for the new identity He has given you in Christ. Ask Him to help you think and live from that position.'],
    2:['You Are Accepted by Grace','Your standing before God rests upon His grace and Christ’s finished work, not your religious performance.','Ephesians 1:6–7; 2:8–9; Romans 5:1–2','Give thanks that acceptance before God rests in His grace rather than your ability to earn His favor.'],
    3:['You Are Complete in Christ','You do not need to acquire a superior spiritual standing through religious ordinances, human regulations, or personal merit.','Colossians 2:8–10','Thank God for your completeness in Christ and ask for discernment to reject anything that treats Christ as insufficient.'],
    4:['You Are a Member of One Body','Believing Jews and Gentiles share equal standing in the Body of Christ without national distinction or covenantal hierarchy.','1 Corinthians 12:12–13; Ephesians 3:6','Thank God for placing you in one Body and ask Him to shape your relationships with other believers accordingly.'],
    5:['You Are Blessed in the Heavenly Places','The Body of Christ possesses a heavenly calling and spiritual blessings in Christ.','Ephesians 1:3; 2:4–6','Thank God for the spiritual blessings that are already yours in Christ and ask for greater understanding of your heavenly position.'],
    6:['Walk from Your Position','Christian conduct flows from the believer’s position in Christ; it does not create that position.','Romans 12:1–2; Ephesians 4:1; Colossians 2:6–7','Ask God to renew your thinking so that your daily walk increasingly reflects the position He has already given you in Christ.'],
    7:['Your Hope Is in Christ','Your future is secure in Christ and culminates in glorification and the heavenly destiny of the Body of Christ.','Philippians 3:20–21; 1 Thessalonians 4:13–18','Thank God for your secure hope in Christ and ask Him to let that future hope shape your present faithfulness.']
  };

  const grid = root.querySelector('.rl-grid'), search = root.querySelector('.rl-search'), count = root.querySelector('.rl-count');
  const filters = [...root.querySelectorAll('.rl-filter')];
  let activeCategory='All', lastTrigger=null;
  const render=()=>{const q=(search.value||'').trim().toLowerCase();const visible=resources.filter(r=>(activeCategory==='All'||r.category===activeCategory)&&(!q||[r.title,r.subtitle,r.category,r.desc,...r.tags].join(' ').toLowerCase().includes(q)));count.textContent=`${visible.length} resource${visible.length===1?'':'s'}`;grid.innerHTML=visible.length?visible.map(r=>`<article class="rl-card" tabindex="0" role="button" data-resource="${r.id}" aria-label="Open ${r.title}"><div class="rl-category">${r.category}</div><h3>${r.title}</h3><p>${r.desc}</p><div class="rl-tags">${r.tags.map(t=>`<span class="rl-tag">${t}</span>`).join('')}</div><span class="rl-open">Open Resource →</span></article>`).join(''):'<p class="rl-empty">No resources match your search.</p>';};
  render(); search.addEventListener('input',render); filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.category;render();}));

  const overlay=document.createElement('div');overlay.className='rl-overlay';overlay.hidden=true;
  const panel=document.createElement('aside');panel.className='rl-panel';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.innerHTML='<div class="rl-panel-inner"><button class="rl-close" aria-label="Close resource">×</button><div class="rl-panel-body"></div></div>';
  document.body.append(overlay,panel); const body=panel.querySelector('.rl-panel-body'), close=panel.querySelector('.rl-close');
  const setDay=n=>{const d=devotionalDays[n],host=body.querySelector('.rl-devotional');if(!host)return;body.querySelectorAll('.rl-day').forEach(b=>{const on=Number(b.dataset.day)===n;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});host.innerHTML=`<h3>Day ${n} — ${d[0]}</h3><h4>Truth</h4><p>${d[1]}</p><h4>Scripture</h4><p>${d[2]}</p><h4>Reflection</h4><p>Read the passages slowly. What do they say God has already made true of you in Christ? How should that truth shape the way you think and walk today?</p><h4>Prayer</h4><p>${d[3]}</p>${n===7?'<div class="rl-principle"><strong>Closing Truth</strong><p>Your identity in Christ is not something you are trying to achieve. It is the position God has already given you by grace. Christian growth begins by knowing what God has made you in Christ and learning to walk consistently with that truth.</p></div>':''}`;};
  const openResource=(id,trigger)=>{const r=resources.find(x=>x.id===Number(id));if(!r)return;lastTrigger=trigger;body.innerHTML=`<header class="rl-resource-head"><div class="rl-category">${r.category}</div><h2>${r.title}</h2><div class="rl-resource-sub">${r.subtitle}</div></header><div class="rl-content">${r.content()}<button class="rl-print" type="button">Print This Resource</button></div>`;overlay.hidden=false;panel.hidden=false;document.body.style.overflow='hidden';close.focus();if(r.id===10){body.querySelectorAll('.rl-day').forEach(b=>b.addEventListener('click',()=>setDay(Number(b.dataset.day))));setDay(1);}body.querySelector('.rl-print').addEventListener('click',()=>{document.body.classList.add('rl-printing');window.print();setTimeout(()=>document.body.classList.remove('rl-printing'),100);});};
  const closePanel=()=>{overlay.hidden=true;panel.hidden=true;document.body.style.overflow='';lastTrigger?.focus();};close.addEventListener('click',closePanel);overlay.addEventListener('click',closePanel);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)closePanel();});grid.addEventListener('click',e=>{const c=e.target.closest('.rl-card');if(c)openResource(c.dataset.resource,c);});grid.addEventListener('keydown',e=>{const c=e.target.closest('.rl-card');if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openResource(c.dataset.resource,c);}});
})();