C = [
("h1", "11. Why the Body Is Not the Bride"),
("p", "Claim: the Body of Christ is not the bride, and the reasons are in the text. The wife is named in the prophets, and the Body is a mystery that the prophets did not make known. The wife’s marriage is a covenant, and Paul describes the Body’s formation without making it a party to Israel’s covenants. The Body has figures of its own, and none is bridal. The Body is seated in heavenly places, and the bride is a city that comes down out of heaven. And the title has an owner, which Paul never takes from her."),
("sub", "11.1 A mystery, not a prophecy"),
("p", "Paul says that the Body is the subject of a secret. “By revelation he made known unto me the mystery” (Ephesians 3:3), which “in other ages was not made known unto the sons of men, as it is now revealed unto his holy apostles and prophets by the Spirit; that the Gentiles should be fellowheirs, and of the same body” (Ephesians 3:5–6). He calls it “the fellowship of the mystery, which from the beginning of the world hath been hid in God” (Ephesians 3:9), and in Colossians “the mystery which hath been hid from ages and from generations, but now is made manifest to his saints” (Colossians 1:26). The Body is a company that the earlier ages did not know."),
("p", "The wife is the opposite. She is named in the law and the prophets, over many centuries, to many hearers, as Jerusalem, Zion, Israel and Judah. She is not hidden and then revealed. She is the subject of a long testimony that Revelation calls the spirit of prophecy (Revelation 19:10). A company that was hid in God from the beginning of the world cannot be a company that the prophets named at length. If the Body were the bride, Hosea and Isaiah would have been speaking of the Body without knowing it, and Paul’s own word about what the earlier ages did not know would be untrue."),
("sub", "11.2 A covenant marriage"),
("p", "The prophets’ marriage is made by oath and covenant (Ezekiel 16:8) and is broken as a covenant is broken (Jeremiah 31:32). Paul’s account of the Gentiles’ former condition is that they were “aliens from the commonwealth of Israel, and strangers from the covenants of promise” (Ephesians 2:12). What he says of their present condition is that they are “made nigh by the blood of Christ” (Ephesians 2:13) and that Christ has made “of twain one new man” (Ephesians 2:15), and reconciled “both unto God in one body by the cross” (Ephesians 2:16). He does not say that the Gentiles have entered the covenants of promise. He says that a new man has been made in himself, and that the law of commandments contained in ordinances has been abolished in his flesh (Ephesians 2:15)."),
("p", "The wife’s covenant is Israel’s. The Body is a new man in which the old distinction is abolished. A company that is formed by the abolishing of the wall and that has no covenant of its own to break is not the wife of a covenant marriage."),
("sub", "11.3 The Body’s own figures"),
("p", "Paul’s figures for the Body are consistent and are never bridal. It is a body with a head: “the church, which is his body, the fulness of him that filleth all in all” (Ephesians 1:22–23), the head “even Christ,” from whom “the whole body fitly joined together” makes increase (Ephesians 4:15–16). It is one new man (Ephesians 2:15). It is a building: “an holy temple in the Lord” and “an habitation of God through the Spirit” (Ephesians 2:21–22). It is “the household of God” (Ephesians 2:19). Where Paul wishes to speak of its union with Christ, he uses these, and where he uses the figure of marriage he introduces it as a comparison (Chapter 10)."),
("sub", "11.4 Where each is seated"),
("p", "The Body is told where it stands: God “hath raised us up together, and made us sit together in heavenly places in Christ Jesus” (Ephesians 2:6), and it has been blessed “with all spiritual blessings in heavenly places in Christ” (Ephesians 1:3). The bride is shown coming the other way. The city is “coming down from God out of heaven” to a new earth (Revelation 21:1–2), and she is “descending out of heaven from God” (Revelation 21:10). Their seats are different, and the places they are given are different."),
("sub", "11.5 The scene of the book"),
("p", "The volume holds, with the rest of this series, that the Body is not among the actors of the final judgments and the return of the Lord that the book of Revelation describes. The marriage of the Lamb is a scene of that book. A company that is not found in the book’s scenes cannot be the wife whom the book announces. This reason is the volume’s position about the book, and it does not stand alone. It is the last of the reasons, and the first four do not depend on it."),
("sub", "11.6 The title has an owner"),
("p", "The last reason is the principle of no transfer. A name, a covenant or a promise given to one people by the prophets is not moved to another people because the same words appear in both places. Paul had the prophets in his hands. He could have said that the Gentiles were the wife of Isaiah 54 or the bride of Isaiah 62, and he did not. The silence is not an accident. In the verses where he uses the pattern of marriage he says “as” and “even as,” and he names the Body a body."),
("ctbl", "The wife and the Body compared on the points above.", [
    ("Point", "The wife of the prophets and of Revelation", "The Body in Paul’s letters"),
    ("Made known", "Named in the law and the prophets as Jerusalem, Zion, Israel and Judah", "A mystery hid in God from the beginning of the world (Eph 3:9)"),
    ("Covenant", "Oath and covenant at the espousals; an everlasting covenant promised (Ezek 16:8, 60)", "Once strangers from the covenants; made one new man (Eph 2:12, 15)"),
    ("Figures", "Wife, bride, city, land", "Body, one new man, holy temple, household"),
    ("Husband or head", "Husband and bridegroom, the Lamb", "Head, Christ (Eph 1:22; 4:15)"),
    ("Seat", "A city descending out of heaven to the new earth (Rev 21:1–2)", "Seated in heavenly places in Christ (Eph 2:6)"),
  ], [0.17, 0.43, 0.40]),
("tbl", "The table follows the passages the argument leans on.", [
    ("Eph 3:5", "“which in other ages was not made known unto the sons of men”", "The Body’s mystery was not made known earlier"),
    ("Eph 3:6", "“That the Gentiles should be fellowheirs, and of the same body”", "The mystery is a fellowship of one body"),
    ("Col 1:26", "“the mystery which hath been hid from ages and from generations”", "The mystery was hid until it was made manifest"),
    ("Eph 2:12", "“strangers from the covenants of promise”", "The Gentiles’ former condition"),
    ("Eph 2:15", "“to make in himself of twain one new man”", "A new man is made, and the law of ordinances is abolished"),
    ("Eph 2:21", "“an holy temple in the Lord”", "The Body is a building and a temple"),
    ("Eph 1:22", "“to be the head over all things to the church”", "Christ is head and the church is body"),
    ("Eph 2:6", "“made us sit together in heavenly places in Christ Jesus”", "The Body’s seat is in the heavenly places"),
  ], [0.14, 0.52, 0.34]),
("sub", "11.7 What this chapter does not say"),
("bul", [
    "It does not say that the Body is loved less than the bride. Paul says that Christ loved the church and gave himself for it (Ephesians 5:25).",
    "It does not say that the Body has no union with Christ. It is a body joined to its head, and it is in Christ.",
    "It does not say that a Jewish believer in the Body is the bride. A believer in the Body, whether Jew or Gentile, is a member of the Body and nothing more is claimed.",
  ]),
("call", "Where the argument stands", "The wife is named by the prophets and the Body is a mystery they did not make known. The wife’s marriage is a covenant and the Body is one new man. The Body’s figures are the body, the temple and the household, its seat is the heavenly places, and the title of bride has an owner that Paul does not take from her."),
]
