C = [
("h1", "14. Clause by Clause"),
("p", "This chapter walks through the three passages on which the whole question turns, one clause at a time. In each row the left column gives the words of the text, the middle column says what the clause says, and the right column says what it leaves unsaid. The position stands or falls on what the clauses do and do not say, and a reader is invited to test every row."),
("sub", "14.1 Revelation 19:7–10"),
("ctbl", "The marriage and the supper.", [
    ("The clause", "What it says", "What it leaves unsaid"),
    ("“Let us be glad and rejoice, and give honour to him”", "A call to rejoice, given after the multitude’s cry", "Who the speakers are beyond the great multitude of 19:6"),
    ("“the marriage of the Lamb is come”", "The time of the marriage has arrived", "The place of the marriage and its date beside the rider of 19:11"),
    ("“his wife hath made herself ready”", "The wife belongs to the Lamb and has prepared herself", "That the wife is called the church or the Body"),
    ("“to her was granted that she should be arrayed in fine linen, clean and white”", "The linen is given to her", "Who gives it, beyond the passive “was granted”"),
    ("“the fine linen is the righteousness of saints”", "The linen is explained as righteousness", "That “saints” here names the Body"),
    ("“Blessed are they which are called unto the marriage supper of the Lamb”", "A blessing on those who are called", "That the called are the wife"),
    ("“the testimony of Jesus is the spirit of prophecy”", "The scene is tied to the prophets’ testimony", "That the scene introduces a new people"),
  ], [0.38, 0.31, 0.31]),
("sub", "14.2 Revelation 21:2–14"),
("ctbl", "The city and the bride.", [
    ("The clause", "What it says", "What it leaves unsaid"),
    ("“I John saw the holy city, new Jerusalem”", "The thing seen is a city", "That the city is only a building"),
    ("“prepared as a bride adorned for her husband”", "The city is likened to a bride", "That the bride is a different company from the city’s people"),
    ("“they shall be his people, and God himself shall be with them”", "The covenant formula of the prophets", "Which covenant it names, though Jeremiah 31:33 has the same clauses"),
    ("“I will shew thee the bride, the Lamb’s wife”", "The angel promises to show the bride", "That she will be shown as a company of persons rather than a city"),
    ("“that great city, the holy Jerusalem”", "What he shows is the city", "That any other bride is shown elsewhere in the book"),
    ("“the names of the twelve tribes of the children of Israel”", "The gates carry the tribes’ names", "That the tribes are only a memorial"),
    ("“the names of the twelve apostles of the Lamb”", "The foundations carry twelve names", "That the twelve are themselves the bride"),
    ("“the nations of them which are saved shall walk in the light of it”", "The nations walk in the city’s light", "That the nations are shut out of blessing"),
  ], [0.38, 0.31, 0.31]),
("sub", "14.3 Ephesians 5:22–33"),
("ctbl", "The household and the church.", [
    ("The clause", "What it says", "What it leaves unsaid"),
    ("“Wives, submit yourselves unto your own husbands, as unto the Lord”", "An instruction to wives in the household", "That wives stand for the church"),
    ("“even as Christ is the head of the church: and he is the saviour of the body”", "Headship is compared, and the church is the body", "That the church is called the wife"),
    ("“Husbands, love your wives, even as Christ also loved the church, and gave himself for it”", "Love is compared", "That the church is called the bride"),
    ("“that he might present it to himself a glorious church”", "What is presented is a glorious church", "That the thing presented is a bride"),
    ("“So ought men to love their wives as their own bodies”", "Wives are to be loved as bodies are loved", "That the church is the wife and not the body"),
    ("“we are members of his body, of his flesh, and of his bones”", "The union is a union of body", "That the union makes the church the wife of Isaiah or Hosea"),
    ("“they two shall be one flesh”", "The law of marriage is quoted", "That the law is applied to Israel’s covenant"),
    ("“This is a great mystery: but I speak concerning Christ and the church”", "The union is a great mystery", "That the mystery is the wife of the prophets"),
  ], [0.38, 0.31, 0.31]),
("p", "Three things are plain from the rows. The clauses of Revelation 19 and 21 name a wife, a city, a people and twelve tribes, and they use no word for the church. The clauses of Ephesians 5 name the church, a body and a head, and they use no word for the bride. And the verses that might carry the one over to the other are verses of comparison. A reader who holds that the church is the bride must say that the comparison words in Ephesians 5 are identification words, and that the tribes on the gates in Revelation 21 are not what they say. The position of this volume takes both sets of clauses as they are written."),
("call", "Where the argument stands", "The clauses of Revelation name a wife, a city and twelve tribes, and the clauses of Ephesians name a church, a body and a head. Each set speaks in its own words, and the volume lets each speak."),
]
