C = [
("h1", "5. Psalm 45: The King’s Marriage"),
("p", "Claim: Psalm 45 is a wedding song, and it sets the three parties of the marriage figure in one scene: the king, the bride, and the companions who follow her. The New Testament quotes the king’s part of the psalm of the Son. The psalm does not name the bride, and the position of this volume does not rest on it. It is read here because it shows the shape of the figure, and the shape agrees with what the prophets and Revelation say."),
("sub", "5.1 A song for the king"),
("p", "The writer opens with a purpose: “I speak of the things which I have made touching the king: my tongue is the pen of a ready writer” (Psalm 45:1). The king is addressed as one “fairer than the children of men,” on whom God has laid a blessing “for ever” (Psalm 45:2). He is a warrior who rides “because of truth and meekness and righteousness” (Psalm 45:4), and his enemies fall under him (Psalm 45:5). The first half of the psalm is a portrait of the king, and the second half turns to the marriage. The order matters. The bride is brought to a king who has first been shown reigning."),
("sub", "5.2 The king is the Son"),
("p", "The letter to the Hebrews quotes the psalm. “But unto the Son he saith, Thy throne, O God, is for ever and ever: a sceptre of righteousness is the sceptre of thy kingdom” (Hebrews 1:8). The next verse follows the psalm: “therefore God, even thy God, hath anointed thee with the oil of gladness above thy fellows” (Hebrews 1:9). The writer takes the king of the wedding song to be the Son. That settles who the bridegroom is. It does not, by itself, settle who the bride is, because the letter quotes only the verses about the king."),
("p", "The point is worth marking, since it shows how the New Testament quotes. It takes the verses it needs and leaves the rest where the psalm put them. A reader who finds the king in Hebrews 1 has found him in a psalm that goes on to speak of a bride, and the letter does not carry those verses to the church."),
("sub", "5.3 The bride and her companions"),
("p", "At verse nine the scene changes. “Kings’ daughters were among thy honourable women: upon thy right hand did stand the queen in gold of Ophir” (Psalm 45:9). The psalm then speaks to the bride: “Hearken, O daughter, and consider, and incline thine ear” (Psalm 45:10). The promise to her is, “So shall the king greatly desire thy beauty: for he is thy Lord; and worship thou him” (Psalm 45:11). She is described as “all glorious within,” in clothing of “wrought gold” (Psalm 45:13)."),
("p", "The next verse names two parties. “She shall be brought unto the king in raiment of needlework: the virgins her companions that follow her shall be brought unto thee” (Psalm 45:14). The bride is brought, and the virgins her companions are brought after her. The psalm does not merge them. They are “her companions,” they “follow her,” and they enter the palace with gladness (Psalm 45:15). A bride and a company who attend her are the same pair that Revelation 19 sets side by side, the wife who has made herself ready and those who are called to the supper."),
("sub", "5.4 The nations at the wedding"),
("p", "The psalm adds the nations. “The daughter of Tyre shall be there with a gift; even the rich among the people shall intreat thy favour” (Psalm 45:12). The king’s name is “to be remembered in all generations,” and “the people praise thee for ever and ever” (Psalm 45:17). The king’s children are to be made “princes in all the earth” (Psalm 45:16). The marriage is not a private event. It happens in the sight of the peoples, and the peoples bring gifts, as the nations walk in the light of the city in Revelation 21:24 and the Gentiles see the wife’s righteousness in Isaiah 62:2."),
("tbl", "The table follows the scene of the psalm.", [
    ("Ps 45:1", "“I speak of the things which I have made touching the king”", "The song is addressed to the king"),
    ("Ps 45:6", "“Thy throne, O God, is for ever and ever”", "Quoted of the Son in Hebrews 1:8"),
    ("Ps 45:9", "“upon thy right hand did stand the queen in gold of Ophir”", "A royal court is present at the wedding"),
    ("Ps 45:10", "“Hearken, O daughter, and consider, and incline thine ear”", "The bride is addressed apart from the king"),
    ("Ps 45:14", "“the virgins her companions that follow her shall be brought unto thee”", "The companions are a separate party"),
    ("Ps 45:12", "“the daughter of Tyre shall be there with a gift”", "The nations come to the wedding"),
    ("Ps 45:17", "“I will make thy name to be remembered in all generations”", "The king’s name is the subject at the close"),
  ], [0.13, 0.55, 0.32]),
("sub", "5.5 A question the psalm raises"),
("p", "The bride is told to “forget also thine own people, and thy father’s house” (Psalm 45:10). Some readers take the words as a call to leave an old people for a new one, and so as a place where the church leaves Israel behind. The words do not say that. The psalm does not name the people or the house, and it does not say that the bride’s people are put away. It speaks of a bride leaving her father’s house for her husband’s, which is the law of marriage that Genesis 2:24 states and that Paul quotes in Ephesians 5:31. The psalm has the form of a royal wedding, and the volume does not build a doctrine of the bride’s identity on a verse that names no one."),
("sub", "5.6 What this chapter does not say"),
("bul", [
    "It does not say that the psalm names the bride. It says that the psalm shows a king, a bride and companions, and that the three are kept apart.",
    "It does not say that Hebrews 1 makes the church the bride. The letter quotes the verses about the king and leaves the rest.",
    "It does not say that the psalm settles the question. The position rests on the prophets and on Revelation, and the psalm is read beside them.",
  ]),
("call", "Where the argument stands", "Psalm 45 shows a king, a bride who is brought to him, and companions who follow her, and Hebrews 1 names the king as the Son. The psalm keeps the bride and her companions as two parties, as Revelation 19 does, and it names neither the bride nor the church."),
]
