CONC = [
("h1", "Conclusion"),
("p", "The volume began with a question that most readers have never been asked in this form: to whom was the Husband married? The prophets answer it by name. The LORD is the husband of Israel, and Israel is his wife. The marriage was made in the wilderness by oath and covenant, it was broken by the wife’s unfaithfulness, and the husband put her away. The same prophets who give the charge give the promise, and the promise is made to the same wife, in the same city, under an everlasting covenant."),
("p", "The Gospels take the figure from the prophets and apply the husband’s title to Jesus. Revelation announces the marriage of the Lamb to his wife and shows the bride as a city whose gates carry the names of Israel’s tribes. The guests at the supper are a different party, and the Body of Christ is neither wife nor guest. It is a mystery that the prophets did not make known, a body with Christ as its head, a temple and a household, seated in the heavenly places. Where Paul uses the pattern of marriage he teaches the Body to love, to be loyal and to be holy, and he does not take the title that belongs to Israel."),
("ctbl", "The position in one table.", [
    ("Question", "The position", "Chief passages"),
    ("Who is the husband?", "The LORD, who is the Lamb", "Isa 54:5; John 3:29; Rev 19:7"),
    ("Who is the wife?", "Israel, named as Jerusalem, Zion, the house of Israel and Judah", "Jer 2:2; 3:20; Isa 62:1"),
    ("Was she replaced?", "No. She was put away, called back and promised an everlasting covenant", "Jer 3:14; Ezek 16:60; Hos 3:5"),
    ("What does Revelation 19 announce?", "The marriage of the Lamb to his wife", "Rev 19:7–8"),
    ("What is the bride of Revelation 21?", "The city whose gates carry the tribes of Israel", "Rev 21:9–14"),
    ("Who are the guests?", "The faithful of Israel’s prophetic hope, the friends of the bridegroom", "John 3:29; Rev 19:9"),
    ("Is the Body the bride?", "No. The Body is a body with Christ as its head", "Eph 1:22–23; 3:3–6"),
    ("What do Paul’s marriage figures do?", "They teach release from the law, loyalty and love, and they do not transfer the title", "Rom 7:4; 2 Cor 11:2; Eph 5:22–33"),
  ], [0.30, 0.43, 0.27]),
("p", "The volume asks to be tested, and the test is simple. A reader who disagrees may take any row of the table and look for the verse that overturns it. If the verse is there, the position must change. If it is not there, the position stands on what the text says. In either case the reader will have read the prophets, the Gospels, Revelation and Paul’s letters with the question in hand, and that is no small gain."),
("p", "The volume has spoken plainly where it disagrees, and it has tried to speak fairly of those who differ. The reading it opposes expresses true things about the Lord’s love for the church, and the volume keeps them. What it will not do is move to the Body a name that the Scriptures keep for the wife. The Lord who is faithful to the wife of his youth is the Lord the Body serves, and it needs no other name to be sure of his faithfulness."),
("call", "Where the argument stands", "The wife of the prophets and the Lamb’s wife of Revelation are one wife, and she is Israel. The Body of Christ is joined to its Head as a body, and it is not the bride. Paul’s uses of marriage teach the Body how to live, and they leave the wife’s name where the prophets put it."),
]

APP = [
("h1", "Appendix A. The Bridal Thread at a Glance"),
("ctbl", "The passages in the order the volume has read them.", [
    ("Passage", "The setting", "The wife", "The husband", "Her condition"),
    ("Jer 2:2", "The LORD speaks to Jerusalem", "Jerusalem", "The LORD", "The love of her espousals in the wilderness"),
    ("Hos 2:2", "The husband speaks", "The mother of the children", "The LORD", "Declared not his wife"),
    ("Jer 3:8", "The LORD looks back", "Backsliding Israel, and Judah", "The LORD", "Put away with a bill of divorce"),
    ("Ezek 16:8", "The parable of the foundling", "Jerusalem", "The Lord GOD", "Oath and covenant at the espousals"),
    ("Isa 50:1", "The LORD speaks", "The nation’s mother", "The LORD", "Put away for iniquities"),
    ("Isa 54:5–8", "The song of the barren", "The forsaken wife", "Maker, LORD of hosts, Redeemer", "Forsaken for a small moment, then gathered"),
    ("Hos 2:19–20", "The promise", "The restored wife", "The LORD", "Betrothed for ever"),
    ("Isa 62:4–5", "The new name", "Zion and her land", "Thy God", "Called Hephzibah and Beulah, and married"),
    ("Jer 33:11", "The return of the captivity", "The bride in Jerusalem", "The bridegroom", "Her voice is heard again"),
    ("Rev 19:7", "The great multitude", "His wife", "The Lamb", "Has made herself ready"),
    ("Rev 21:9–14", "The angel’s showing", "The bride, the holy Jerusalem", "The Lamb", "Gates carry the twelve tribes"),
    ("Rev 22:17", "The close of the book", "The bride", "The Lamb", "Speaks with the Spirit"),
  ], [0.14, 0.20, 0.21, 0.19, 0.26]),
("h1", "Appendix B. The Parallels"),
("ctbl", "Features of the wife in the prophets and in Revelation.", [
    ("Feature", "The prophets", "Revelation"),
    ("Judgment on the harlot, then the wife", "Ezek 16:38, 60", "Rev 19:2, 7"),
    ("The wife’s garments", "Ezek 16:10, 13 (fine linen); Isa 61:10 (the robe of righteousness)", "Rev 19:8 (fine linen, righteousness)"),
    ("The new name and the city", "Isa 62:2–4 (a new name, Hephzibah and Beulah)", "Rev 21:2, 10; 3:12 (new Jerusalem, a new name)"),
    ("The covenant formula", "Jer 31:33; Hos 2:23 (my people, their God)", "Rev 21:3 (his people, their God)"),
    ("The bridegroom rejoices", "Isa 62:5", "Rev 19:7 (“let us be glad and rejoice”)"),
    ("The voice of the bride", "Jer 33:11", "Rev 22:17"),
    ("The nations see and come", "Isa 62:2", "Rev 21:24"),
  ], [0.28, 0.40, 0.32]),
("h1", "Appendix C. The Names of the Wife"),
("ctbl", "The names given to the wife, and where.", [
    ("Name", "Where", "What the text says"),
    ("Jerusalem", "Jer 2:2; Ezek 16:2", "The LORD’s word is cried in her ears, and she is made to know her abominations"),
    ("The house of Israel", "Jer 3:20", "She is charged with dealing treacherously as a wife"),
    ("Judah, her sister", "Jer 3:8", "The sister who also played the harlot"),
    ("Zion", "Isa 62:1", "The city for whose sake the prophet will not rest"),
    ("Forsaken and Desolate", "Isa 62:4", "The names she shall no more be called"),
    ("Hephzibah and Beulah", "Isa 62:4", "The names she shall be called, for the LORD delights in her"),
    ("The bride, the Lamb’s wife", "Rev 21:9–10", "The holy Jerusalem, shown by the angel"),
  ], [0.26, 0.20, 0.54]),
("h1", "Appendix D. Questions for Study"),
("num", [
    "Read Jeremiah 2:2 and Ezekiel 16:8. Where and when does each place the marriage?",
    "Hosea 3:1 interprets Hosea’s sign. What does it say the sign stands for?",
    "Compare Deuteronomy 24:4 with Jeremiah 3:1. What does the LORD do that the law does not allow between men?",
    "List the names Isaiah 62:2–5 gives the wife, and say what the Gentiles and kings do in verse 2.",
    "In John 3:29, what is the difference between the friend of the bridegroom and the one who has the bride?",
    "Read Matthew 22:1–14 and Matthew 25:1–13. Is a bride named in either parable?",
    "In Revelation 19:7–9, how many parties are named, and what does each do?",
    "What names are written on the gates and on the foundations of the city in Revelation 21:12–14?",
    "Compare Revelation 21:3 with Jeremiah 31:33. Which clauses do they share?",
    "Read Ephesians 5:23–32 and mark each “even as.” What is compared with what?",
    "Read Ephesians 3:3–9 and Colossians 1:26. What does Paul say about when the mystery was made known?",
    "Read Galatians 4:24–27. What does Paul call this passage, and what does he call the Jerusalem above?",
    "What would a reader have to supply in order to read the church into Revelation 19:7?",
    "Read Psalm 45:9–15. How many parties are named besides the king, and how does the psalm keep them apart?",
    "Compare Hebrews 1:8–9 with Psalm 45:6–7. Which verses does the letter quote, and which does it leave?",
    "Read Jeremiah 31:31–32. Which two houses are named, and what title does the LORD take in verse 32?",
    "Set Revelation 17:1–3 beside Revelation 21:9–10. What do the two openings share, and where do they differ?",
    "Compare Jeremiah 25:10 with Revelation 18:22–23. Which phrases are the same?",
  ]),
("h1", "Appendix E. Terms"),
("ctbl", "Terms as used in this volume.", [
    ("Term", "Meaning in this volume"),
    ("The bride, the wife", "The woman whom the LORD betrothed to himself in the prophets, and whom Revelation names the Lamb’s wife. In this volume she is Israel."),
    ("The bridegroom", "The husband of the figure. In the prophets, the LORD. In the Gospels and Revelation, Jesus, the Lamb."),
    ("Espousals, betrothal", "The promise of marriage and its bond, placed by the prophets in the wilderness and promised again for ever."),
    ("Friend of the bridegroom", "The companion who stands with the bridegroom and rejoices in his voice, as John did (John 3:29)."),
    ("Children of the bridechamber", "The wedding company of Matthew 9:15 and Mark 2:19, who are with the bridegroom."),
    ("The Body", "The church which is Christ’s body, formed under the gospel Paul calls the mystery (Ephesians 1:22–23; 3:3–6)."),
    ("The mystery", "What was hid in God from the beginning and made known to Paul, that the Gentiles should be fellowheirs and of the same body (Ephesians 3:5–9)."),
    ("No transfer", "The principle that a name, covenant or promise given to one people is not moved to another because the same words appear in both places."),
  ], [0.28, 0.72]),
]

BIB = [
("h1", "Bibliography"),
("bib", "The Holy Bible, King James Version (the Authorized Version, in its standard text). Public domain. All Scripture quotations in this volume."),
("bib", "Constable, Thomas. //Dr. Constable’s Expository Notes//. 2012. Free full text. Quoted from the notes on Revelation 19:7, 19:9 and 21:12, and on 2 Corinthians 11:2."),
("bib", "Walvoord, John F. //The Revelation of Jesus Christ//. Moody Press, 1966. Free full text. Quoted from the chapter on Revelation 19."),
("bib", "MacArthur, John. //Heavenly Hallelujahs, Part 3//. Sermon on Revelation 19, Grace to You, sermon 66-68. Free full transcript. Quoted."),
("bib", "Pentecost, J. Dwight. //Things to Come//. Dunham Publishing, 1958. Position described, not quoted."),
("bib", "Ryrie, Charles C. //Basic Theology//. Victor Books, 1986. Position described, not quoted."),
("bib", "Thomas, Robert L. //Revelation 8–22: An Exegetical Commentary//. Moody Press, 1995. Position described, not quoted."),
]
