import json
E=[]
def q(s): return s.replace("'", "’")
def para(kind,text,bold=False): E.append(dict(type='para',kind=kind,segs=[[q(text),bold,False]],p=0,x0=0))
def h1(t): para('h1',t)
def body(t): para('body',t)
def bul(t): para('bul',t)
def num(t): para('num',t)
def lead(l,t): E.append(dict(type='para',kind='body',segs=[[q(l),True,False],[q(t),False,False]],p=0,x0=0))
def call(title,text): E.append(dict(type='para',kind='ctitle',segs=[[title,True,False]],p=0,x0=0)); para('cbody',text)
def tbl(rows,xs): E.append(dict(type='tbl',rows=[[q(c) for c in r] for r in rows],xs=xs))
KX=[[0,110],[110,400],[400,640]]
def kjv(rows): tbl([['Verse','KJV text','What to observe']]+[[a,'“'+b+'”',c] for a,b,c in rows],KX)

h1('What You Will Learn in This Study')
body('By the end of this study, you should be able to:')
bul("Identify the woman of Revelation 12:1–2 from her own Old Testament background, not from a later doctrinal assumption.")
bul("Trace the dragon's identity and aim across verses 3–4 and confirm it from Revelation 12:9's own naming.")
bul("Trace the identity of the male child in 12:5 by following the chapter's own textual markers — including the term “caught up” (harpazō) and the later appearance of a sealed firstfruits company in Revelation 14:1–5.")
bul("Test whether the two time-measures of the woman's wilderness protection (1,260 days; “a time, and times, and half a time”) describe one period or two, using Daniel 12:7 and the chapter's own wording.")
bul("Follow the order of events from 12:7 to 12:17, noting where the war in heaven ends and where the dragon's later war begins.")
bul("Identify “the rest of her offspring” in 12:17 correctly — who they are and, as important, who they are not.")
call('STUDY GOAL',"To read Revelation 12 as a single continuous sign, identify the woman, the male child, the dragon, and “the rest of her offspring” from the passage's own Old Testament background, and trace the chapter's persecution and protection against Israel's Prophecy Program, testing whether any part of the vision can be assigned to the Body of Christ.")
para('sub','Study Outline',True)
for t in ["A Great Wonder in Heaven: The Woman (12:1–2)","What the Woman Is Not","The Dragon and His Aim (12:3–4)","The Male Child (12:5)","The Woman's Flight to the Wilderness (12:6, 13–16)","War in Heaven (12:7–9)","The Heavenly Proclamation and the Overcomers (12:10–12)","War Against Her Offspring (12:17)"]: bul(t)
h1('Introduction')
body("You will read Revelation 12 as one continuous sign rather than a set of detachable symbols. You will identify the woman, the dragon, and the male child from the images John himself supplies — the sun, moon, and twelve stars; the seven heads and ten horns; the rod of iron from Psalm 2 — and you will follow the narrative through the war in heaven, the dragon's fall, and his pursuit of the woman into the wilderness. You will close by identifying “the rest of her offspring” in verse 17 with the same discipline: from the passage's own wording and its place in Israel's Prophecy Program, not from an assumption carried in from elsewhere.")
body("Readers who already own Study 9 (The Remnant), Study 23 (The 144,000), Study 7 (The Day of the Lord), or Study 10 (Daniel's Seventieth Week) will recognize adjoining ground here. Study 9 traces the believing remnant's preservation across Israel's history in general terms; this study narrates one specific scene of that preservation — the woman's flight and the dragon's pursuit — and supplies the remnant's Revelation 12:17 description in its own setting. Study 23 identifies the 144,000 as a numbered, sealed company within the remnant; this study extends that identification to the male child of 12:5, and treats “the rest of her offspring” in 12:17 as the wider remnant population the 144,000 belong to, not as another name for the same company. Study 7 traces the Day of the Lord's judgment and Israel's restoration across the prophets broadly; this study supplies one chapter's contribution to that same period without re-deriving the whole Day-of-the-Lord chronology. Study 10 reads Daniel's seventieth week as a seven-year unit divided at its midpoint; this study reads Revelation 12's 1,260 days and “time, times, and half a time” as that same three-and-a-half-year half-week from the perspective of the woman rather than Daniel's own vantage point. The question this study alone answers: who are the woman, the male child, the dragon, and her offspring in Revelation 12, and what does the chapter itself establish about each of them?")
h1('1. A Great Wonder in Heaven: The Woman (12:1–2)')
body("John introduces the chapter's central figure with the word “wonder” — “a great wonder in heaven” (12:1), and, of the dragon, “another wonder in heaven” (12:3). The Greek word is sēmeion, “sign,” and it signals that what follows is symbolic and must be read from Scripture's own supplied images rather than from a surface impression. The woman is “clothed with the sun, and the moon under her feet, and upon her head a crown of twelve stars” (12:1). Every element of that description already has a biblical referent before Revelation was written.")
kjv([("Rev. 12:1","And there appeared a great wonder in heaven; a woman clothed with the sun, and the moon under her feet, and upon her head a crown of twelve stars:","What she is clothed with, what is under her feet, and how many stars crown her."),
("Rev. 12:2","And she being with child cried, travailing in birth, and pained to be delivered.","What she is doing, and in what condition.")])
body("Genesis 37:9–11 supplies it directly. Joseph dreams of the sun, moon, and eleven stars bowing to him, and Jacob supplies the interpretation himself: “Shall I and thy mother and thy brethren indeed come to bow down ourselves to thee?” (37:10). The sun is Jacob, the moon his wife, the eleven stars Joseph's brothers — the constellation is the patriarchal family: Israel. Revelation 12 adds a twelfth star, completing the number to the twelve tribes, and crowns one woman with it. The image was already Israel's before John picked it up.")
body("Isaiah supplies the rest. Isaiah 66:7–8 describes Zion in labor in language that anticipates Revelation 12:2: “Before she travailed, she brought forth … for as soon as Zion travailed, she brought forth her children.” The travailing woman who brings forth is a recurring prophetic figure for the covenant nation, not for a New Testament assembly unknown to the prophets whose images Revelation borrows.")
h1('2. What the Woman Is Not')
body("Because Revelation 12 stands near chapters that plainly concern the Church (2–3), some readings import the Church into chapter 12 as well. But the chapter gives no textual signal for that identification, and two details rule it out. First, the woman brings forth the male child (12:5) — a company sealed from Israel's own tribes (Revelation 7:4), which the Church, having no tribal identity, could not produce. Second, the same woman later flees persecution and is nourished for “a time, and times, and half a time” (12:14) — the identical period Daniel 12:7 assigns to “the power of the holy people,” Israel, near the end of Daniel's own prophetic timetable. A figure who brings forth a company drawn from Israel's own tribes and is then preserved through Daniel's appointed period for Israel is Israel, read on the terms the text itself supplies. The Body is absent from Daniel's seventieth week, the Tribulation and the judgments of Revelation; this chapter belongs to Israel's Prophecy Program.")
h1('3. The Dragon and His Aim (12:3–4)')
body("“And there appeared another wonder in heaven; and behold a great red dragon, having seven heads and ten horns, and seven crowns upon his heads” (12:3). Revelation does not leave this figure's identity to inference for long: verse 9 names him outright — “that old serpent, called the Devil, and Satan, which deceiveth the whole world.” The ten horns tie this dragon to the fourth beast of Daniel 7:7, 24, which likewise carries ten horns and represents the final form of Gentile world power in Daniel's own prophetic sequence. The dragon is the spiritual power standing behind, and ultimately embodied in, that same end-time political order.")
body("His aim is stated plainly: his tail draws a third of the stars of heaven and casts them to the earth — a judgment on a portion of the angelic host, most naturally read as the angels who followed Satan in his original rebellion — and he “stood before the woman which was ready to be delivered, for to devour her child as soon as it was born” (12:4). The verse describes intent, not an accomplished act: the devouring never happens. The child is caught up to God before the dragon can reach him (12:5).")
call('NOTE',"The dragon's identity is not left to the reader's inference. Revelation 12:9 names him directly — “that old serpent, called the Devil, and Satan” — before the chapter is finished.")
h1('4. The Male Child (12:5)')
body("“And she brought forth a man child, who was to rule all nations with a rod of iron: and her child was caught up unto God, and to his throne.” The verb “caught up” is harpazō, the same word Paul uses for the Body's own catching-up in 1 Thessalonians 4:17 — but never the word Scripture uses for Christ's ascension (Acts 1:9 uses a different construction, “taken up”). A term reserved for the removal of a living company, applied to a “man child” born of Israel, points to a corporate firstfruits company rather than the Messiah's own ascension.")
body("Revelation supplies that company later: the 144,000 “standing on the mount Sion” with the Lamb, “firstfruits unto God” (14:1, 4), sealed from Israel's own tribes (7:4) — one company seen at two points in the vision. Nor does the rod of iron require the ruler to be Christ: Revelation 2:26–27 promises that authority to “he that overcometh,” power shared with Christ, not held instead of Him. The child's safety, not a biography of the Messiah, is the point here.")
kjv([("Rev. 12:3–4","And there appeared another wonder in heaven; and behold a great red dragon, having seven heads and ten horns, and seven crowns upon his heads. And his tail drew the third part of the stars of heaven, and did cast them to the earth: and the dragon stood before the woman which was ready to be delivered, for to devour her child as soon as it was born.","The heads, horns and crowns; what the tail does; what the dragon stands ready to do."),
("Rev. 12:5","And she brought forth a man child, who was to rule all nations with a rod of iron: and her child was caught up unto God, and to his throne.","What the child is to do; the verb used of him; where he is taken.")])
call('NOTE',"Harpazō is never Scripture's word for Christ's ascension; it names the removal of a living company, and Revelation 14:1–5 shows that company — the 144,000 — already standing with the Lamb.")
h1("5. The Woman's Flight to the Wilderness (12:6, 13–16)")
body("“And the woman fled into the wilderness, where she hath a place prepared of God, that they should feed her there a thousand two hundred and threescore days” (12:6). The chapter returns to this same flight later, in more detail, after the war in heaven: “to the woman were given two wings of a great eagle, that she might fly into the wilderness, into her place, where she is nourished for a time, and times, and half a time, from the face of the serpent” (12:14). The eagle's-wings image recalls Exodus 19:4, where God tells Israel at Sinai, “I bare you on eagles' wings, and brought you unto myself” — the same protective image, reused for a later and still-future deliverance of the same people.")
body("1,260 days and “a time, and times, and half a time” are two measures of one period, not two separate periods. Three and a half years of 360-day prophetic years equals 1,260 days; “time, times, and half a time” (one plus two plus one-half) counts the same three and a half years by number of years rather than days. Daniel 12:7 uses the identical years-based phrase for “the power of the holy people” being “scattered,” confirming both that the subject is Israel and that the period is the second half of Daniel's seventieth week (compare Study 10). Revelation 12 narrates that same half-week from the vantage point of the pursued woman rather than from Daniel's own prophetic sequence.")
call('KEY DISTINCTION',"The 1,260 days (12:6) and the “time, times, and half a time” (12:14) are the same three-and-a-half-year period measured two ways, not consecutive periods to be added together.")
h1('6. War in Heaven (12:7–9)')
body("“And there was war in heaven: Michael and his angels fought against the dragon; and the dragon fought and his angels, and prevailed not; neither was their place found any more in heaven” (12:7–8). Michael is named in Daniel 10:21 and 12:1 as “your prince,” the angel assigned specifically to Israel's cause — another point of contact tying this chapter's events to Israel's own prophetic history rather than to a general or universal drama. The outcome is total and final for the dragon's standing in heaven: “the great dragon was cast out, that old serpent, called the Devil, and Satan, which deceiveth the whole world: he was cast out into the earth, and his angels were cast out with him” (12:9).")
body("This war in heaven is distinct within the vision from the dragon's later war against the woman's offspring in verse 17, and from the beast's war against the saints in chapter 13. The sequence: the dragon is cast down (12:9); heaven rejoices while earth is warned, since the devil, knowing his time is short, has come down “having great wrath” (12:12); he pursues the woman (12:13); failing to overtake her, he makes war on the rest of her offspring instead (12:17). Reading these as one undifferentiated “war” collapses a sequence given in careful stages.")
kjv([("Rev. 12:6","And the woman fled into the wilderness, where she hath a place prepared of God, that they should feed her there a thousand two hundred and threescore days.","Where she goes; who prepared the place; how long she is fed, in days."),
("Rev. 12:7–9","And there was war in heaven: Michael and his angels fought against the dragon; and the dragon fought and his angels, And prevailed not; neither was their place found any more in heaven. And the great dragon was cast out, that old serpent, called the Devil, and Satan, which deceiveth the whole world: he was cast out into the earth, and his angels were cast out with him.","Who fights whom; the names given to the dragon; where he is cast."),
("Rev. 12:13–14","And when the dragon saw that he was cast unto the earth, he persecuted the woman which brought forth the man child. And to the woman were given two wings of a great eagle, that she might fly into the wilderness, into her place, where she is nourished for a time, and times, and half a time, from the face of the serpent.","What the dragon does once cast down; the means of escape; how the period is stated here."),
("Rev. 12:15–16","And the serpent cast out of his mouth water as a flood after the woman, that he might cause her to be carried away of the flood. And the earth helped the woman, and the earth opened her mouth, and swallowed up the flood which the dragon cast out of his mouth.","What is sent after her, and what answers it.")])
call('KEY DISTINCTION',"Three sequential conflicts, not one: the war in heaven (12:7–9), the dragon's pursuit of the woman (12:13–16), and his war against her offspring (12:17) occur in that order and must not be merged.")
h1('7. The Heavenly Proclamation and the Overcomers (12:10–12)')
body("The casting-down of the dragon is followed immediately by a loud voice in heaven announcing that “the accuser of our brethren is cast down, which accused them before our God day and night” (12:10), and describing how “they overcame him by the blood of the Lamb, and by the word of their testimony; and they loved not their lives unto the death” (12:11). The proclamation's structure matters: it announces Satan's judicial removal from his accusing office, then commends those already martyred for their testimony as having overcome him — not by surviving him, but by refusing to renounce their testimony even at the cost of their lives.")
body("“Our brethren” in this proclamation are best read in context as those who have already died for their testimony during the period this chapter describes — the martyrs of the Tribulation, whose company Revelation elsewhere describes directly (Revelation 6:9–11; 7:9–14; 20:4). The proclamation is heaven's own verdict on their deaths, not a description of the Body of Christ's corporate identity or calling, which Revelation nowhere addresses in this chapter.")
h1('8. War Against Her Offspring (12:17)')
body("Unable to overtake the woman herself, “the dragon was wroth with the woman, and went to make war with the remnant of her seed, which keep the commandments of God, and have the testimony of Jesus Christ” (12:17). This is the chapter's final and, for this study, most consequential identification. “The remnant of her seed” (rendered “the rest of her offspring” in some translations) are the woman's own children other than the male child already caught up to God — that is, they belong to Israel, the same mother whose firstfruits were removed in 12:5, not to a separately introduced people.")
body("Two identifying marks are given for this company: they “keep the commandments of God” and “have the testimony of Jesus Christ.” Both marks describe believers living through the Tribulation who hold to God's revealed will and to the truth about Jesus as Messiah under active persecution — language that fits the believing remnant this study's neighboring studies already establish (Study 9), and the company from which the sealed 144,000 are drawn without being identical to them (Study 23). Nothing in the verse's wording, audience, or setting reassigns this remnant to the Body of Christ; the chapter has been narrating Israel's own woman, Israel's own male child, and Israel's own persecution throughout, and verse 17 completes that same account rather than shifting its subject.")
kjv([("Rev. 12:10–12","And I heard a loud voice saying in heaven, Now is come salvation, and strength, and the kingdom of our God, and the power of his Christ: for the accuser of our brethren is cast down, which accused them before our God day and night. And they overcame him by the blood of the Lamb, and by the word of their testimony; and they loved not their lives unto the death. Therefore rejoice, ye heavens, and ye that dwell in them. Woe to the inhabiters of the earth and of the sea! for the devil is come down unto you, having great wrath, because he knoweth that he hath but a short time.","What is announced in heaven; the means by which they overcome; the warning to earth and sea."),
("Rev. 12:17","And the dragon was wroth with the woman, and went to make war with the remnant of her seed, which keep the commandments of God, and have the testimony of Jesus Christ.","Whom the dragon turns against; the two marks given.")])
lead('Key Distinction. ',"“The rest of her offspring” (12:17) are Israel's Tribulation-era believing remnant — the same remnant Study 9 traces and from which the 144,000 of Study 23 are drawn — never the Body of Christ, which this chapter does not name or describe.")
lead('Table 1. ',"The chapter's four identifications and their textual basis")
tbl([['Figure','Identification','Textual basis'],
['The woman (12:1)','Israel, the covenant nation','Gen. 37:9–11 (sun/moon/stars); Isa. 66:7–8 (travailing Zion)'],
['The male child (12:5)','The 144,000, Israel\'s firstfruits remnant','Harpazō never describes Christ\'s ascension; Rev. 14:1–5 shows this company already with the Lamb'],
['The dragon (12:3, 9)','Satan','Named directly in 12:9; ten horns tie him to Daniel 7\'s fourth beast'],
['Her offspring (12:17)','Israel\'s Tribulation remnant','Dan. 12:1, 7 (“holy people,” same 3½-year period); parallels Study 9']],[[0,150],[150,330],[330,640]]) if False else None
E.append(dict(type='tbl',rows=[[q(c) for c in r] for r in [['Figure','Identification','Textual basis'],
['The woman (12:1)','Israel, the covenant nation','Gen. 37:9–11 (sun/moon/stars); Isa. 66:7–8 (travailing Zion)'],
['The male child (12:5)',"The 144,000, Israel's firstfruits remnant","Harpazō never describes Christ's ascension; Rev. 14:1–5 shows this company already with the Lamb"],
['The dragon (12:3, 9)','Satan',"Named directly in 12:9; ten horns tie him to Daniel 7's fourth beast"],
['Her offspring (12:17)',"Israel's Tribulation remnant",'Dan. 12:1, 7 (“holy people,” same 3½-year period); parallels Study 9']]],xs=[[0,150],[150,330],[330,640]]))
h1('Conclusion')
body("Revelation 12 identifies every major figure in its own text before the chapter ends: the dragon names himself in verse 9, the male child's removal by harpazō is answered by the 144,000's reappearance in 14:1–5, and the woman's crown of twelve stars borrows a constellation Genesis had already assigned to Israel's own family. Read on those terms, the chapter tells one continuous story — Israel brings forth her sealed firstfruits, the dragon fails to destroy them, loses his place in heaven, and turns his remaining fury on Israel's own Tribulation-era remnant. No point in that sequence requires, or even permits, substituting the Body of Christ for the woman or her offspring.")
h1('Study Summary')
for t in ["The woman of Revelation 12:1–2 is Israel, identified from Genesis 37:9–11's sun-moon-stars imagery and Isaiah 66:7–8's travailing Zion, not a later ecclesiological assumption.",
"The dragon is named directly in 12:9 as Satan; his ten horns tie him to Daniel 7's fourth beast and its still-future prophetic timetable.",
"The male child of 12:5 is the 144,000 — harpazō is never Scripture's word for Christ's ascension, and Revelation 14:1–5 shows that company already with the Lamb.",
"The 1,260 days (12:6) and “time, times, and half a time” (12:14) measure the same 3½-year period two ways, matching Daniel 12:7's identical phrase for Israel's own appointed distress.",
"The war in heaven (12:7–9), the dragon's pursuit of the woman (12:13–16), and his war against her offspring (12:17) are three distinct, sequential movements — not one conflict.",
"“The rest of her offspring” (12:17) are Israel's believing Tribulation remnant — the company Study 9 traces and from which Study 23's 144,000 are drawn — never the Body of Christ."]: bul(t)
h1('Key Distinctions to Retain')
for t in ["The woman is Israel, not the Church: she brings forth a company sealed from Israel's own twelve tribes, and the Church has no tribal identity to produce it.",
"The dragon's identity is stated by the text itself (12:9); it does not need to be inferred or debated.",
"The male child is fixed by the term “caught up” (harpazō) and by the 144,000's reappearance in Revelation 14:1–5, not by a loose resemblance to Christ.",
"One period, two measures: 1,260 days and “time, times, and half a time” must not be treated as sequential or additive.",
"Three sequential conflicts — heaven (12:7–9), the woman's flight (12:13–16), and her offspring (12:17) — must be kept in their given order, not merged into one event.",
"“Her offspring” in 12:17 are Israel's remnant, not the Body of Christ; the chapter never introduces a second people to bear that title."]: bul(t)
h1('Scripture-Tracing Exercise')
body("Open each passage listed below in its own context before comparing it with Revelation 12. For each one, record: (1) who is speaking or writing, and to whom; (2) what image or promise the passage itself supplies; and (3) how Revelation 12 reuses that same image or promise. Do not move to the next passage until you have written a one-sentence conclusion for the current one.")
for t in ["Genesis 37:9–11 — what does Jacob's own interpretation assign to the sun, moon, and eleven stars?","Isaiah 66:7–8 — who travails and brings forth, and in what corporate sense?","Psalm 2:7–9 and Revelation 2:26–27 — to whom is the “rod of iron” promised in each passage, and what does Revelation 2:26–27 add about overcomers sharing that authority?","Daniel 7:7, 24 — what does the fourth beast's ten horns represent in Daniel's own sequence?","Daniel 12:1, 7 — whose “time of trouble” is in view, and what period is given for it?","Exodus 19:4 — to whom does God first give the eagle's-wings image, and for what purpose?"]: num(t)
body("Once all six are traced, write a two-to-three sentence conclusion identifying the woman, the male child, and her offspring using only the evidence you have just recorded.")
h1('Review and Discussion Questions')
for t in ["From what two Old Testament passages is the woman's description in Revelation 12:1–2 drawn, and what does each passage establish about her identity?","Where does Revelation itself name the dragon, and why does this make the dragon's identity a matter of reading rather than inference?","What does the verb “caught up” (harpazō) in 12:5 rule out about the male child's identity, and how does Revelation 14:1–5 confirm the alternative identification later in the book?","Explain why the 1,260 days of 12:6 and the “time, times, and half a time” of 12:14 should be read as the same period rather than as two separate periods.","List, in order, the three distinct conflicts narrated in Revelation 12:7–17, and state who is in view in each one.","Who are “the rest of her offspring” in 12:17? Name the two studies most directly related to this identification and state, in one sentence each, what each of those studies adds that this chapter does not."]: num(t)
h1('Teaching Outline')
for t in ["Introduce the chapter as one continuous sign, not a collection of separate symbols.","Identify the woman from Genesis 37 and Isaiah 66 before any other question is asked.","Show that the dragon names himself in the text (12:9) rather than requiring inference.","Fix the male child's identity from the term “caught up” (harpazō) and its confirmation in Revelation 14:1–5.","Walk through the chapter's three sequential conflicts in their given order: heaven, the woman's flight, her offspring.","Reconcile the 1,260 days and “time, times, and half a time” as one period measured two ways.","Identify “the rest of her offspring” (12:17) as Israel's Tribulation remnant, and state plainly what this identification excludes.","Close by tracing how this chapter's identifications connect to, without duplicating, Studies 9, 23, 7, and 10."]: bul(t)
h1('Guided Further Study')
body("Open and read each passage below in context. For each group, observe the assigned subject or distinction, compare it with this study's controlling distinction between Israel's Prophecy Program and the Body's Mystery Program, and record a concise conclusion before moving on.")
G=[("Group 1 — The woman's background: ","Genesis 37:9–11; Isaiah 66:7–8; Isaiah 54:1–6. Observe how each applies a woman-figure to the covenant nation corporately, and record what that rules out for Revelation 12:1."),
("Group 2 — The dragon and Daniel's beasts: ","Daniel 7:1–8, 19–25; Revelation 13:1–2. Observe the shared horn-count and kingdom imagery, and record how Revelation 12 and 13 continue Daniel's sequence rather than introducing an unrelated figure."),
("Group 3 — The appointed period: ","Daniel 9:27; 12:7, 11–12; Revelation 11:2–3; 13:5. Observe how each measures the same half-week by days or years, and record why these should be read as one period consistently applied."),
("Group 4 — The remnant's testimony: ","Revelation 6:9–11; 7:9–14; 20:4. Observe the shared description of those slain for their testimony, and record how these support this study's identification of “her offspring” in 12:17."),
("Group 5 — The male child identified: ","1 Thessalonians 4:17; 2 Corinthians 12:2; Acts 1:9; Revelation 2:26–27; Revelation 14:1–5. Observe which of these describe harpazō (a living company's removal) and which describe Christ's own ascension by a different verb, and record why Revelation 12:5's “caught up” and 14:1–5's already-gathered 144,000 read as one company shown twice, not the person of Christ.")]
for l,t in G: lead(l,t)
h1('Final Synthesis')
body("Bring together everything this study has traced. In your own words, state: (1) who the woman, the male child, the dragon, and her offspring are, with the one textual anchor that fixes each identification; (2) why the 1,260 days and “time, times, and half a time” describe one period rather than two; (3) the correct order of the chapter's three conflicts; and (4) why “the rest of her offspring” in 12:17 cannot be the Body of Christ. Write your synthesis as a single coherent paragraph a reader unfamiliar with the chapter could follow from Scripture alone.")
json.dump(E,open('els61.json','w'),ensure_ascii=False)
print(len(E))
